### DISCUSSION TITLE
How does WB_AUTH=False work?

### DISCUSSION THREAD

**Discussion by JonathanRKing** [mrlt8/docker-wyze-bridge#1197] [General]
Hi,

I added WB_AUTH=False to my docker-compose.yml file on my Mac but my setup from Homebridge Camera UI keeps saying the streams cannot be accessed do to an auth failure. I'm unclear on what is expected, or how to disable auth, or how to get the RTSP stream working with authentication properly.

**Comment by mrlt8** [comment]
You should see `WebUI auth is disabled` at the bottom of your web ui like this:
<img width="326" alt="auth" src="https://github.com/mrlt8/docker-wyze-bridge/assets/67088095/d8a5415a-af04-4df5-aeb2-bc90bc4ca217">
Did you restart the container after setting `WB_AUTH=False`?

**Reply by JonathanRKing** [reply]
Hi, sorry for the delay. I have restarted multiple times since making the config change, and I do not see that banner at the bottom of the page. I do see the API key listed there though, which seems odd.

**Reply by JonathanRKing** [reply]
Just to be clear, this is the sample YAML file, and it doesn't include the WB_AUTH=false line. where does it go exactly?

services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            # [OPTIONAL] Credentials can be set in the WebUI
            # API Key and ID can be obtained from the wyze dev portal: 
            # https://developer-api-console.wyze.com/#/apikey/view
            - WYZE_EMAIL=
            - WYZE_PASSWORD= 
            - API_ID=
            - API_KEY= 
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            # - WB_IP=192.168.1.122

**Reply by mrlt8** [reply]
It can go anywhere inside environment:
```yaml
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            - WB_AUTH=False
            # [OPTIONAL] Credentials can be set in the WebUI
            # API Key and ID can be obtained from the wyze dev portal: 
            # https://developer-api-console.wyze.com/#/apikey/view
            - WYZE_EMAIL=
            - WYZE_PASSWORD= 
            - API_ID=
            - API_KEY= 
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            # - WB_IP=192.168.1.122
```
