### DISCUSSION TITLE
Docker images that work well with the bridge (linux)

### DISCUSSION THREAD

**Discussion by alan5ab** [mrlt8/docker-wyze-bridge#1257] [General]
NVR  -- The best nvr I've found is sentryshot, it's h264 only and no audio. It installs with a simple docker-compose.yml file. It can be found here [https://github.com/SentryShot/sentryshot](url)

LIVE VIEW  -- The best live viewing software I've found is go2rtc, you can create and bookmark different live views. It is very versatile. It can be found here: [https://hub.docker.com/r/alexxit/go2rtc](url)

Combined with the bridge these 2 images work very efficiently with low cpu usage. Post what you use in conjunction with the bridge....

**Comment by mrlt8** [comment]
openvpn works great if you need to access cameras running the latest firmware on a different network:
```yaml
services:
  openvpn:
    image: dperson/openvpn-client
    container_name: openvpn
    restart: unless-stopped
    ports:
      - 8554:8554 # RTSP
      - 8889:8889 #WebRTC
      - 8189:8189/udp # WebRTC/ICE
      - 5050:5000 # WEB-UI 
    dns: [8.8.8.8]
    cap_add: [NET_ADMIN]
    command: "-f /vpn/config.ovpn"
    volumes:
      - ./config.ovpn:/vpn/config.ovpn
  wyze-bridge:
    depends_on:
      - openvpn
    network_mode: service:openvpn
    container_name: wyze-bridge
    image: mrlt8/wyze-bridge:latest
    restart: always
```
