### DISCUSSION TITLE
instead of openvpn, is it possible to use cloud-flare warp?

### DISCUSSION THREAD

**Discussion by guocity** [mrlt8/docker-wyze-bridge#1308] [General]
instead of openvpn, is it possible to use cloud-flare warp?

**Comment by mrlt8** [comment]
Possibly. See the [tailscale](https://github.com/mrlt8/docker-wyze-bridge/blob/main/docker-compose.tailscale.yml) example.

You'd setup another warp container and use that for the `network_mode`:

```yaml
    depends_on: [warp]
    network_mode: service: warp
```

**Comment by guocity** [comment]
can you help me check, it doesn't seems able to connect to remote camera, is there any network tool in the image that i can ping the remote camera?
```yaml
  warp:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    ports:
    - 1935:1935 # RTMP
    - 8554:8554 # RTSP
    - 8888:8888 # HLS
    - 8889:8889 #WebRTC
    - 8189:8189/udp # WebRTC/ICE
    - 5080:5000 # WEB-UI
    # home
    command: tunnel run --token $CLOUDFLARE_TOKEN
  wyze-bridge:
      container_name: wyze-bridge
      restart: unless-stopped
      image: mrlt8/wyze-bridge:latest
      depends_on: [warp]
      network_mode: service:warp
      devices:
          - /dev:/dev
   ```
