### DISCUSSION TITLE
MFA Help

### DISCUSSION THREAD

**Discussion by sohansolo** [mrlt8/docker-wyze-bridge#138] [Q&A] [answered]
![image](https://user-images.githubusercontent.com/12873986/134083056-0a5118b4-0e74-4a2e-b278-acecc9d89918.png)
Stuck on this part of the implementation

Thanks!

**Comment by mrlt8** [comment, marked as answer]
You'll need a way to pass your verification to the container. 

To use the docker command, you'll need to open a new terminal window and run the command:
```bash
docker exec -it wyze-bridge sh -c 'echo "123456" > /tokens/mfa_token'
```
(replace "123456" with your code)
If you get something like "No such container", you can run `docker ps` and use the container id instead:
```bash
docker exec -it ff11aa3d4d5d sh -c 'echo "123456" > /tokens/mfa_token'
```

Or if you'd rather not deal with the commands, you could always add something like this to your docker compose:
```yaml
environment:
    - WYZE_EMAIL=email@email.com
     - WYZE_PASSWORD=password
volumes:
    - ./tokens:/tokens/
```
You can then create a file named `mfa_token` in the tokens folder and add save your code to that file.
