### DISCUSSION TITLE
Camera connection stability issues, firmware upgrades?

### DISCUSSION THREAD

**Discussion by pdxbrit** [mrlt8/docker-wyze-bridge#247] [Q&A]
Hi Folks, 

I posted this as an [issue-240](https://github.com/mrlt8/docker-wyze-bridge/issues/240), before I noticed the discussion section, so my apologies for that! I'm a bit stuck, and don't know how to proceed. I think my initial mistake was upgrading a device firmware without thinking about how it might impact the wyze-bridge. 

Originally I had one Wyze Cam v3 working with the 1.0.2 version of wyze-bridge. It would occasionally go down for a few seconds every few hours but was otherwise reliable and working. That camera is running `4.36.6.17` when I added a second v3 camera, running `4.36.3.19` the one running `4.36.6.17` would connect, and then immediately disconnect, and keep doing that.  When I filtered out the second camera, the `4.36.3.19` one,   the`4.36.6.17` would work again. 

I've since discovered I was running `1.0.2` not `1.0.3`, I've upgraded to `1.0.3` and also upgraded the camera to `4.36.7.22` and I still see the problem. In fact now even when I have only one camera configured the `4.36.7.22` one cannot stay connected for more than a a second or so, and now the `4.36.3.19` one disconnects every couple of mins. 

Attached is a log with just the `4.36.3.19` (front-porch-cam) and one with just the `4.36.7.22` (garagecam). 

Current docker compose file:

```
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest # Use a prebuilt image
        # build:  # Uncomment to build from source
        #     context: ./app # Uncomment to build from source
        #     # dockerfile: Dockerfile.arm # Uncomment to build for arm
        ports:
            - 1935:1935
            - 8554:8554
            - 8889:8889
        environment:
            - FILTER_NAMES=Lake Cam, Front Porch Cam
            - FILTER_BLOCK=true
            - NET_MODE=LAN
            - WYZE_EMAIL=email
            - WYZE_PASSWORD=password
            - DOCKER_HOST=192.168.1.114
            - TZ=America/Los_Angeles
            - DEBUG_LEVEL=debug
            - RTSP_LOGLEVEL=debug
            - FRESH_DATA=1
 ```

[garagecam.txt](https://github.com/mrlt8/docker-wyze-bridge/files/7598950/garagecam.txt)
[frontporchcam.txt](https://github.com/mrlt8/docker-wyze-bridge/files/7598951/frontporchcam.txt)

Any ideas how to troubleshoot this more, or how to resolve it?

Cheers, Mark.
