### DISCUSSION TITLE
1.0.4 helped a lot,  1 more question

### DISCUSSION THREAD

**Discussion by wayne47git** [mrlt8/docker-wyze-bridge#261] [Q&A]
1.0.4 fixed all my problems mentioned in [238](https://github.com/mrlt8/docker-wyze-bridge/discussions/238).
What's the spell to make a stream work in HA (hassio)?  I have:
```
camera:
    - platform: generic
    name: frontcam
    still_image_url: http://192.168.51.28:8123/local/outdoor1.jpg
    stream_source: rtsp://192.168.51.28:8554/outdoor1
```
which gets a snapshot (updated properly in www/CAMERA_NAME.jpg) but never gives a stream viewable in HA.  (I do get 2 snapshots; one names "Wyze camname" and one named "frontcam" but I can live with that). My guess is that HA is confused because it's not going to the IP address of the camera. The stream **is** viewable using vlc, despite nmap not seeing anything on port 8554 when pointed at 192.168.51.28.

If anyone has the HAdashboard spell to make a stream come up by tapping the still image, I'd love to know that.

**Comment by mrlt8** [comment]
does using `127.0.0.1` help?
```
camera:
  - platform: generic
    name: cam-name
    still_image_url: http://127.0.0.1:8123/local/cam-name.jpg
    stream_source: rtsp://127.0.0.1:8554/cam-name
```
