### DISCUSSION TITLE
How to access snapshots

### DISCUSSION THREAD

**Discussion by mammerman** [mrlt8/docker-wyze-bridge#266] [Q&A]
The readme explains where the snapshots are stored locally, but I don't see a description of how (or if) the images are exposed outside the container - in this case standard docker container.  Are they exposed on an existing stream port or do they need to be manually setup to be accessible outside the container?

**Comment by mrlt8** [comment]
The standard container does not have an http server, but you can either map the img dir locally or add a server like nginx to your docker-compose with something like this:

```yaml
services:
  wyze-bridge:
...
    volumes:
      - ./img:/img
  web:
    container_name: nginx
    image: nginx:mainline-alpine
    ports:
        - 8080:80
    volumes:
        - ./img:/usr/share/nginx/html
```
