### DISCUSSION TITLE
How to install on Home Assistant 2021.12.4

### DISCUSSION THREAD

**Discussion by DellProSupportGse** [mrlt8/docker-wyze-bridge#271] [General]
I am very new to Home Assistant and just installed on the latest version 2021.12.4 and I installed docker-wyze-bridge v1.0.4. I added my wyze creds in the configuration tab and started it. How do I add my cameras to the dashboard?

**Comment by mrlt8** [comment]
You can edit your `configuration.yaml` file in home assistant and add the camera using the [generic](https://www.home-assistant.io/integrations/generic/) or [ffmpeg](https://www.home-assistant.io/integrations/camera.ffmpeg/) integrations with something like:
```yaml
camera:
  - platform: generic
    still_image_url: http://127.0.0.1:8123/local/my-cam-name.jpg
    stream_source: rtsp://127.0.0.1:8554/my-cam-name
```
or
```yaml
camera:
  - platform: ffmpeg
    input: rtsp://127.0.0.1:8554/my-cam-name
```
