### DISCUSSION TITLE
Setting up recording on Windows

### DISCUSSION THREAD

**Discussion by mcarter87** [mrlt8/docker-wyze-bridge#509] [Q&A] [answered]
I moved this container from my Ubuntu machine to my Windows machine that's running Contacam for a different cam. I'd like to use the Wyze Bridge record feature vs using Contacam because it doesn't seem to like both cams I have. I started up the docker-compose file from the D drive, which is the drive Contacam is recording to, but I can't get anything to record.

version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
        environment:
            - WYZE_EMAIL=email # Replace with wyze email 
            - WYZE_PASSWORD=password # Replace with wyze password
            - ENABLE_AUDIO=True
            - TZ=America/Chicago
            - RECORD_ALL=True
        volumes:
            - D:\Contacam:\record
This is what I currently have. I've tired a few other ways to list the directory, so if someone could help point me to what I'm doing wrong, I'd appreciate it.

Thanks in advance

**Comment by mrlt8** [comment, marked as answer]
Hmm, seems like windows is a little tricky, do one of these work?

```yaml
volumes:
    - "D:/Contacam:/record"
```

or 
```yaml
volumes:
    - d/Contacam:/record
```
or potentially:
```yaml
    - /d/Contacam:/record
```

**Reply by mcarter87** [reply]
So far I've got the top option to create a file, but it only makes the one mp4 file and it stays at 0 bytes. I'll do more with it when I'm home, but if there's anything else I can try I'd appreciate it.

**Reply by mcarter87** [reply]
I've tried all three options and all I get is the one video file at 0 bytes, and that only shows if I restart the container. The docker logs say it'll record 60s clips to the designated folder. I also moved it back to my Ubunutu machine, but found I got the same results. I've restarted everything, made sure all three ports are open and pointing to the machine docker is on, and that I can access the stream using VLC. One thing I noticed is that since this camera is on a remote network it connects via p2p. Maybe recording doesn't work on the p2p connection? I'll try to get a cam on site to test via LAN unless there's no point in it. Thanks again in advance for any and all help. If this needs to be moved to the 'issues' section please let me know.

Update: I tried another Wyze Cam v3 locally and the recordings are behaving in the same way.

**Reply by mrlt8** [reply]
Hmm, that is strange. I just tried recording from a remote camera over p2p and it worked as expected for me. Could it be a permissions issue on the directory?

This is what I'm using in my docker-compose to record to a relative path:

```yaml
    volumes:
      - ./record:/record
```

**Reply by mcarter87** [reply]
I tried setting it up on the documents folder of my C drive on Windows to make sure I had permissions, but got the same results. I also tried on Ubuntu in the documents folder with no luck. Even when changing the permission of the entire directory it would create a file listed as an mp4 file, (but oddly displays as a text file and opens in text editor), that is shown to be owned by root, and not me. I'm still looking into ways to make this work. Any chance you could share your compose file for me to look over? Maybe I'm missing something?

**Reply by mrlt8** [reply]
Can you view any of the streams live?

Recording is working for me on Ubuntu 22.04.1 and on MacOS:

```yaml
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
            - 5000:5000
        image: mrlt8/wyze-bridge:latest
        environment:
            - WYZE_EMAIL=
            - WYZE_PASSWORD=
            - ON_DEMAND=True
            - RECORD_ALL=True
        volumes:
            - ./record:/record
            - ./tokens:/tokens
```
