### DISCUSSION TITLE
Configuring RTSP Recording

### DISCUSSION THREAD

**Discussion by aerodb** [mrlt8/docker-wyze-bridge#838] [Q&A]
I have seen the available guidance within the advanced section of the wiki, but I am having trouble understanding the process to enable recording. While I understand it is labeled as advanced, I'm trying to learn some new things and this is one of them. 

I have been able to map the docker volume for recording storage(I believe), but that is where I got stuck 

Does anyone have any steps, guide, or documentation that they could share to help my enable the recording?

**Comment by mrlt8** [comment]
basically, you just need to add `RECORD_ALL=True` and map your local directory to the `/record/` on the docker container. something like this:

```yaml
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            ...
        environment:
            - WYZE_EMAIL=
            - WYZE_PASSWORD= 
            - RECORD_ALL=True # Added for recording
        volumes:
            - /local/path/:/record/ # Added for recording
```

The `TZ` option for the timezone is option. See the recording page for more info:
https://github.com/mrlt8/docker-wyze-bridge/wiki/Stream-Recording-and-Livestreaming
