### DISCUSSION TITLE
It will not save my credentials in the config page

### DISCUSSION THREAD

**Discussion by sceccola** [mrlt8/docker-wyze-bridge#897] [General]
I suspect I missed a pre-req , but not sure  - please help

**Comment by mrlt8** [comment]
If using docker-compose, you'll need to volume mount the tokens directory to persist your session with something like this:

```yaml
...
    environment:
      - WYZE_EMAIL=...
      - WYZE_PASSWORD=...
    volumes:
      - /path/to/store/local/token_dir/:/tokens/
```
