### ISSUE TITLE
Camera Motion webhooks with Home Assistant 

### ISSUE THREAD

**Issue by domolys** [mrlt8/docker-wyze-bridge#1044]
(Using docker-wyze-bridge v2.5.1 with Home Assistant)
This issue is concerning the wiki

The webhook automation trigger object in Home Assistant does not contain a dictionary of key value pairs for the headers of the incoming request. (GET/HEAD)

So, actually, it is not possible to use the image url and title that are available in the request header, using MOTION_WEBHOOKS :

```
X-Title: Motion detected on cam-name
X-Attach: https://...
```

The only way to use MOTION_WEBHOOKS option with Home Assistant is to create a different Webhook ID trigger for each camera in an automation to know from witch camera the motion is detected.

It's possible to use the MOTION_WEBHOOKS with Home Assistant, but not the way the doc is written for Home Assistant: https://github.com/mrlt8/docker-wyze-bridge/wiki/Camera-Motion#webhooks

Example of an automation triggered by two differents webhook_id:

```
description: "WYZE-BRIDGE-MOTION_WEBHOOKS"
mode: single
trigger:
  - platform: webhook
    allowed_methods:
      - POST
      - PUT
      - GET
      - HEAD
    local_only: true
    webhook_id: MY-CAM-1-random_id1239743908
  - platform: webhook
    allowed_methods:
      - POST
      - PUT
      - GET
      - HEAD
    local_only: true
    webhook_id: MY-CAM-2-random_id7139244517
```
    
Part of config used in Wyze Bridge for triggering the automation above:

```
CAM_OPTIONS:
  - CAM_NAME: MY-CAM-1
    MOTION_WEBHOOKS: http://home-assistant-host:8123/api/webhook/MY-CAM-1-random_id1239743908
  - CAM_NAME: MY-CAM-2
    MOTION_WEBHOOKS: http://home-assistant-host:8123/api/webhook/MY-CAM-2-random_id7139244517 
```
`[WyzeBridge] [MOTION] Motion detected on MY-CAM-1`
A motion event will trigger the Home Assistant automation above, but the only available trigger data for the user is something like this:

`{'platform': 'webhook', 'webhook_id': 'MY-CAM-1-random_id1239743908', 'data': <MultiDictProxy()>, 'query': <MultiDictProxy()>, 'description': 'webhook', 'id': '0', 'idx': '0', 'alias': None}`

...otherwise, the addon rocks!

**Comment by mrlt8** [comment]
Thanks for the report.
Do we need to post data to the endpoint? Would it work with a query parameter? e.g.:
```
MOTION_WEBHOOKS: http://home-assistant-host:8123/api/webhook/MY-CAM-1-random_id1239743908?some_key=some_value&anotherKey=otherValue
```

**Comment by domolys** [comment]
Yes it works, receiving for **trigger.querry**:

`<MultiDictProxy('some_key': 'some_value', 'anotherKey': 'otherValue')>`

Also a POST would works:
`POST -H "Content-Type: application/json" -d '{ "some_key": "some_value" }' http://home-assistant-host:8123/api/webhook/MY-CAM-1-random_id1239743908`

**trigger.json** will be: `{'some_key': 'some_value'}`

Thanks!

**Comment by mrlt8** [comment]
In theory, you should be able to reuse the same web hooks endpoint with multiple cameras by passing the camera name variable `{cam_name}` as a query parameter:
```
MOTION_WEBHOOKS: http://0.0.0.0:123/webhooks/endpoint?camera={cam_name}
```

I've also added `{img}` variable in the dev branch, so you will also be able to pass the snapshot url with something like:
```
MOTION_WEBHOOKS: http://0.0.0.0:123/webhooks/endpoint?camera={cam_name}&snapshot={img}
```

**Comment by domolys** [comment]
Tested passing variables as query parameter the the _same webhook endpoint_:

```
MOTION_API: true
CAM_OPTIONS:
  - CAM_NAME: Cam 1
    MOTION_WEBHOOKS: http://0.0.0.0:8123/api/webhook/random_id?camera={cam_name}&snapshot={img}
  - CAM_NAME: Cam 2
    MOTION_WEBHOOKS: http://0.0.0.0:8123/api/webhook/random_id?camera={cam_name}&snapshot={img}
  - CAM_NAME: Cam 3
    MOTION_WEBHOOKS: http://0.0.0.0:8123/api/webhook/random_id?camera={cam_name}&snapshot={img}
```

Setup of Home Assistant automation trigger:

```
platform: webhook
allowed_methods:
  - GET
  - HEAD
local_only: true
webhook_id: random_id
```
Both triggers **trigger.query.camera** and **trigger.query.snapshot** are receiving the variables values

Home Assistant webhook endpoint: `http://your-home-assistant:8123/api/webhook/<webhook_id>`
Home Assistant webhook trigger doc: https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger

Thank you!
