### ISSUE TITLE
Wyze Cam Pan - ERR: no one is publishing to path 'XXXXX'

### ISSUE THREAD

**Issue by jeffreylin** [mrlt8/docker-wyze-bridge#110]
Getting `[RTMP] ERR: no one is publishing to path 'XXXXX'`

---

`docker-wyze-bridge` seems to connect to the Wyze servers OK and auth properly, but it seems like it's having trouble getting the video feed - you can see the RTMP connection as the last thing in the log, but it doesn't find the video feed despite finding the camera earlier.

Let me know if there's any more info I can provide or things I can try to debug! I tried downgrading to `docker-wyze-bridge:0.5.18` to see if the latest refactor caused some issues, but still got the same results. None of the other video protocols work either.

---

Setup is:
 - Wyze Cam Pan (Firmware 4.10.0.222)
 - Running on RasPi 3B
 - Running `mrlt8/wyze-bridge:latest` which is `v0.6.2` as of now.

**docker-compose.yml**
```
pi@raspberrypi:~/workspace/docker-wyze-bridge $ cat docker-compose.yml
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: always
        image: mrlt8/wyze-bridge:latest # Use a prebuilt image
        # build:  # Uncomment to build from source
        #     context: ./app # Uncomment to build from source
        #     # dockerfile: Dockerfile.arm # Uncomment to build for arm
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
        environment:
            - WYZE_EMAIL=XXXXX #${WYZE_EMAIL} # Replace with wyze email
            - WYZE_PASSWORD=YYYYYY #${WYZE_PASSWORD} # Replace with wyze password
            - IGNORE_OFFLINE=true
            - DEBUG_LEVEL=debug
            - RTSP_LOGLEVEL=debug
```

**Log**
```
pi@raspberrypi:~/workspace/docker-wyze-bridge $ docker-compose up --build
Starting wyze-bridge ... done
Attaching to wyze-bridge
wyze-bridge    | 2021/09/08 03:26:16 I [0/0] rtsp-simple-server v0.17.3
wyze-bridge    | 2021/09/08 03:26:16 I [0/0] [RTSP] TCP listener opened on :8554
wyze-bridge    | 2021/09/08 03:26:16 I [0/0] [RTMP] listener opened on :1935
wyze-bridge    | 2021/09/08 03:26:16 I [0/0] [HLS] listener opened on :8888
wyze-bridge    | 2021/09/08 03:26:16 I [0/0] [API] listener opened on 127.0.0.1:9997
wyze-bridge    |
wyze-bridge    | 🚀 STARTING DOCKER-WYZE-BRIDGE v0.6.2
wyze-bridge    | 2021/09/08 03:26:17 [wyze_bridge][INFO][MainThread] 📚 Using 'user' from local cache...
wyze-bridge    | 2021/09/08 03:26:17 [wyze_bridge][INFO][MainThread] 📚 Using 'cameras' from local cache...
wyze-bridge    |
wyze-bridge    | 🎬 STARTING ALL 2 CAMERAS
wyze-bridge    | 2021/09/08 03:26:17 [wyze_bridge][DEBUG][Garage Cam] ⌛️ Connecting to cam..
wyze-bridge    | 2021/09/08 03:26:17 [wyze_bridge][DEBUG][Backyard Cam] ⌛️ Connecting to cam..
wyze-bridge    | 2021/09/08 03:26:18 [wyze_bridge][INFO][Backyard Cam] IOTC_ER_DEVICE_OFFLINE
wyze-bridge    | 2021/09/08 03:26:18 [wyze_bridge][INFO][Backyard Cam] 🪦 Camera is offline. Will NOT try again.
wyze-bridge    | 2021/09/08 03:26:19 [wyzecam.iotc][INFO][Garage Cam] AV Client Start: chan_id=0 expected_chan=0
wyze-bridge    | 2021/09/08 03:26:19 [wyzecam.tutk.tutk_ioctl_mux][INFO][Thread-1] Now listening on channel id 0
wyze-bridge    | 2021/09/08 03:26:19 [wyzecam.tutk.tutk_ioctl_mux][DEBUG][Garage Cam] SEND <K10000ConnectRequest code=10000 resp_code=10001> <TutkWyzeProtocolHeader prefix=b'HL' protocol=1 code=10000 txt_len=0> b''
wyze-bridge    | 2021/09/08 03:26:19 [wyzecam.tutk.tutk_ioctl_mux][DEBUG][Thread-1] RECV <TutkWyzeProtocolHeader prefix=b'HL' protocol=10 code=10001 txt_len=17>: b'\x03\xa0\x83A9\x96M\xa1\xc6\xd5|\xa8\x94\xc8\x9b\x8ay'
wyze-bridge    | 2021/09/08 03:26:19 [wyzecam.tutk.tutk_protocol][DEBUG][Garage Cam] Sending response: <K10002ConnectAuth code=10002 resp_code=10003>
wyze-bridge    | 2021/09/08 03:26:19 [wyzecam.tutk.tutk_ioctl_mux][DEBUG][Garage Cam] SEND <K10002ConnectAuth code=10002 resp_code=10003> <TutkWyzeProtocolHeader prefix=b'HL' protocol=1 code=10002 txt_len=22> b'\tua-\xfa\x1c\xce5\xf7\xd3\xb9\x07\x83\xd9vq2CAA\x01\x01'
wyze-bridge    | 2021/09/08 03:26:19 [wyzecam.tutk.tutk_ioctl_mux][DEBUG][Thread-1] RECV <TutkWyzeProtocolHeader prefix=b'HL' protocol=10 code=10003 txt_len=642>: b'{"connectionRes":"1","cameraInfo":{"videoParm": {"bitRate":"120","resolution":"1","fps":"15","horizontalFlip":"1","verticalFlip":"1"},"settingParm": {"stateVision":"1", "nightVision":"3", "osd":"1", "logSd":"1", "logUdisk":"1", "telnet":"2","tz":"-7"},"basicInfo": {"firmware":"4.10.0.222","type":"Camera","hardware":"0.0.0.0","model":"WYZECP1_JEF","mac":"MACMACMAC"},"channelResquestResult": {"video":"1","audio":"1"},"recordType": {"type":"1"},"sdParm": {"status":"2","capacity":"0","free":"10"},"uDiskParm": {"status":"2","capacity":"0","free":"0"},"apartalarmParm":{"type":"0","startX":"25","longX":"50","startY":"25","heightY":"50"}}}'
wyze-bridge    | 2021/09/08 03:26:19 [wyzecam.tutk.tutk_ioctl_mux][DEBUG][Garage Cam] SEND <K10056SetResolvingBit code=10056 resp_code=10057> <TutkWyzeProtocolHeader prefix=b'HL' protocol=1 code=10056 txt_len=3> b'\x01x\x00'
wyze-bridge    | 2021/09/08 03:26:19 [wyzecam.tutk.tutk_ioctl_mux][DEBUG][Thread-1] RECV <TutkWyzeProtocolHeader prefix=b'HL' protocol=10 code=1 txt_len=2>: b"H'"
wyze-bridge    | 2021/09/08 03:26:33 I [0/0] [RTMP] [conn 10.10.20.10:58264] opened
wyze-bridge    | 2021/09/08 03:26:33 I [0/0] [path garage-cam] created
wyze-bridge    | 2021/09/08 03:26:33 I [0/0] [RTMP] [conn 10.10.20.10:58264] ERR: no one is publishing to path 'garage-cam'
wyze-bridge    | 2021/09/08 03:26:33 I [0/0] [RTMP] [conn 10.10.20.10:58264] closed
```
