### ISSUE TITLE
No motion events - stopped recently

### ISSUE THREAD

**Issue by kiwi-cam** [mrlt8/docker-wyze-bridge#1125]
Recently I've stopped getting motion alerts via webhooks from all my cameras. It seems to have started around the same time as #1108. Unfortunately this is both around the time v2.7.0 was released, and the last firmware update to the cameras. I've rolled back to 2.5.3 which seems to have helped with the sync issue - but still no motion events.

My docker compose file is (which is unchanged other than the image version):
````
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:2.5.3
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 5000:5000 # HTML
        environment:
            - WYZE_EMAIL=xxxxx
            - WYZE_PASSWORD=xxxxx
            - QUALITY=HD
            - ENABLE_AUDIO=False
            - SUBSTREAM=True
            - SNAPSHOT=API
            - IMG_DIR=/img/
            - CONNECT_TIMEOUT=45
            - MOTION_API=True
            - MOTION_START=True
            - MOTION_WEBHOOKS_xxxx_CAM=http://192.168....
            - MOTION_WEBHOOKS_xxxx_CAM=http://192.168....
            - MOTION_WEBHOOKS_GARAGE_CAM=http://192.168....
        volumes:
            - ./img:/img
 ````
