### ISSUE TITLE
Wrong FPS for recordings [v2.8.x]

### ISSUE THREAD

**Issue by JA16122000** [mrlt8/docker-wyze-bridge#1159]
Now 2.8.1 is perfect 
No more delay, but now ar my recordings wrong.
Cam 'voortuin' should be 30 minutes, but it is only 2.50 minutes
cam 'achtertuin' should also be 30 minutes, but is record in slowmotion and takes an hour to play.

So 1 is speedy forwarding recording, the otherone is in slomo 🤣

_Originally posted by @JA16122000 in https://github.com/mrlt8/docker-wyze-bridge/discussions/1042#discussioncomment-9212466_

**Comment by mrlt8** [comment]
Looking into this. If you don't mind, can you post a short clip so I can inspect the FPS in the recording?

**Comment by JA16122000** [comment]
https://github.com/mrlt8/docker-wyze-bridge/assets/112784196/9eae5e91-edfe-4a9c-b43e-5cc9f0353b25


https://github.com/mrlt8/docker-wyze-bridge/assets/112784196/fc75d8c5-958d-485d-aba4-f3bd42f75333

**Comment by JA16122000** [comment]
It is not every clip, just a few.
i'm recording in 30 minutes clips:

```
            - RECORD_ALL=True
            - RECORD_PATH=/Record/{cam_name}
            - RECORD_FILE_NAME={cam_name}_%Y%m%d_%H_%M_%S
            - RECORD_LENGTH=1800   
```

**Comment by mrlt8** [comment]
Hmm, does this only happen when audio is enabled? If so, can you try `AUDIO_CODEC=libopus`? 
Can you post the `videoParm` from the web-ui or `/api/cam-name/fps` from the web api?


Another option would be to set the FPS to `-r 20` in ffmpeg with something like this (Note: audio should be disabled):
```yaml
- FFMPEG_CMD=ffmpeg -hide_banner -loglevel info -fflags +flush_packets+nobuffer+genpts -flags +low_delay -thread_queue_size 8 -analyzeduration 32 -probesize 32 -f H264 -r 20 -i pipe:0 -map 0:v -c:v copy -max_muxing_queue_size 1 -max_delay 0.1 -rtbufsize 32 -f tee [use_fifo=1:fifo_options=attempt_recovery=1\\:drop_pkts_on_overflow=1:f=rtsp:rtsp_transport=tcp]rtsp://0.0.0.0:8554/{cam_name}|[onfail=ignore:f=segment:segment_time=60:segment_atclocktime=1:segment_format=mp4:reset_timestamps=1:strftime=1:use_fifo=1]/Record/{cam_name}/{cam_name}_%Y%m%d_%H_%M_%S.mp4
```

**Comment by JA16122000** [comment]
> Hmm, does this only happen when audio is enabled? If so, can you try `AUDIO_CODEC=libopus`? Can you post the `videoParm` from the web-ui or `/api/cam-name/fps` from the web api?
> 
> Another option would be to set the FPS to `-r 20` in ffmpeg with something like this (Note: audio should be disabled):
> 
> ```yaml
> - FFMPEG_CMD=ffmpeg -hide_banner -loglevel info -fflags +flush_packets+nobuffer+genpts -flags +low_delay -thread_queue_size 8 -analyzeduration 32 -probesize 32 -f H264 -r 20 -i pipe:0 -map 0:v -c:v copy -max_muxing_queue_size 1 -max_delay 0.1 -rtbufsize 32 -f tee [use_fifo=1:fifo_options=attempt_recovery=1\\:drop_pkts_on_overflow=1:f=rtsp:rtsp_transport=tcp]rtsp://0.0.0.0:8554/{cam_name}|[onfail=ignore:f=segment:segment_time=60:segment_atclocktime=1:segment_format=mp4:reset_timestamps=1:strftime=1:use_fifo=1]/Record/{cam_name}/{cam_name}_%Y%m%d_%H_%M_%S.mp4
> ```

i have no audio.

My docker-compose:
```

version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 5000:5000 # WEB-UI
            - 9997:9997 # Expose port for API
            - 8889:8889 # WebRTC
            - 8189:8189 # WebRTC/ICE
        environment:
            - API_ID=blablabla
            - API_KEY=blablabla
            - WYZE_EMAIL=blablabla@gmail.com
            - WYZE_PASSWORD=blablabla
            - WEB_AUTH=True
            - WEB_USERNAME=blablabla
            - WEB_PASSWORD=blablabla
            - WB_IP=192.168.178.78
            - NET_MODE=LAN
            - RECORD_ALL=True
            - RECORD_PATH=/Record/{cam_name}
            - RECORD_FILE_NAME={cam_name}_%Y%m%d_%H_%M_%S
            - RECORD_LENGTH=1800            
        volumes:
            - /mnt/usbhdd/Record/:/record/
            - ./tokens:/tokens/

```
