### ISSUE TITLE
connection issue with V4, V3 cam

### ISSUE THREAD

**Issue by tam1230** [mrlt8/docker-wyze-bridge#1216]
## Describe the bug
Provide a clear and concise description of the issue and include logs if applicable.

This is config yaml file.

ENABLE_AUDIO: false
ON_DEMAND: false
WB_AUTH: false
MOTION_API: false
MQTT_DTOPIC: homeassistant
CAM_OPTIONS:
  - CAM_NAME: Front
    AUDIO: true
    QUALITY: HD200
  - CAM_NAME: Rear
    AUDIO: false
    QUALITY: HD50
  - CAM_NAME: Left
    AUDIO: false
    QUALITY: HD50
  - CAM_NAME: Right
    AUDIO: false
    QUALITY: HD50
WYZE_EMAIL: myemail
WYZE_PASSWORD: mypassword
API_ID: myapiid
API_KEY: myapikey
NET_MODE: P2P
IGNORE_OFFLINE: true
LOG_LEVEL: DEBUG
LOG_FILE: true
LOG_TIME: true

and this is log file.
23:42:49 [INFO][WyzeBridge] 🎉 Connecting to WyzeCam V4 - Front on 192.168.1.101
23:42:49 [WARNING][WyzeBridge] WARNING: This process (pid=8) is multi-threaded, use of fork() may lead to deadlocks in the child.
[front] Connect via IOTC_Connect_ByUIDEx
23:42:49 [DEBUG][front] Connect via IOTC_Connect_ByUIDEx
23:43:09 [WARNING][front] [-13] IOTC_ER_TIMEOUT
23:43:10 [INFO][WyzeBridge] 🎉 Connecting to WyzeCam V4 - Front on 192.168.1.101
23:43:10 [WARNING][WyzeBridge] WARNING: This process (pid=8) is multi-threaded, use of fork() may lead to deadlocks in the child.
[front] Connect via IOTC_Connect_ByUIDEx
23:43:10 [DEBUG][front] Connect via IOTC_Connect_ByUIDEx
23:43:30 [WARNING][front] [-13] IOTC_ER_TIMEOUT
23:43:31 [INFO][WyzeBridge] 🎉 Connecting to WyzeCam V4 - Front on 192.168.1.101
23:43:31 [WARNING][WyzeBridge] WARNING: This process (pid=8) is multi-threaded, use of fork() may lead to deadlocks in the child.
[front] Connect via IOTC_Connect_ByUIDEx
23:43:31 [DEBUG][front] Connect via IOTC_Connect_ByUIDEx
23:43:51 [WARNING][WyzeBridge] ⏰ Timed out connecting to Front.
23:43:52 [INFO][WyzeBridge] 🎉 Connecting to WyzeCam V4 - Front on 192.168.1.101
23:43:52 [WARNING][WyzeBridge] WARNING: This process (pid=8) is multi-threaded, use of fork() may lead to deadlocks in the child.
[front] Connect via IOTC_Connect_ByUIDEx
23:43:52 [DEBUG][front] Connect via IOTC_Connect_ByUIDEx
23:44:12 [WARNING][front] [-13] IOTC_ER_TIMEOUT
23:44:13 [INFO][WyzeBridge] 🎉 Connecting to WyzeCam V4 - Front on 192.168.1.101
23:44:13 [WARNING][WyzeBridge] WARNING: This process (pid=8) is multi-threaded, use of fork() may lead to deadlocks in the child.
[front] Connect via IOTC_Connect_ByUIDEx
23:44:13 [DEBUG][front] Connect via IOTC_Connect_ByUIDEx
23:44:15 [INFO][WyzeBridge] 172.30.32.2 - - [19/May/2024 23:44:15] "GET /api/front HTTP/1.1" 200 -
23:44:33 [WARNING][WyzeBridge] ⏰ Timed out connecting to Front.
23:44:34 [INFO][WyzeBridge] 🎉 Connecting to WyzeCam V4 - Front on 192.168.1.101
23:44:34 [WARNING][WyzeBridge] WARNING: This process (pid=8) is multi-threaded, use of fork() may lead to deadlocks in the child.
[front] Connect via IOTC_Connect_ByUIDEx
23:44:34 [DEBUG][front] Connect via IOTC_Connect_ByUIDEx
23:44:54 [WARNING][front] [-13] IOTC_ER_TIMEOUT
23:44:54 [INFO][WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
23:44:54 [DEBUG][WyzeBridge] Starting new HTTPS connection (1): api.wyzecam.com:443
23:44:55 [DEBUG][WyzeBridge] https://api.wyzecam.com:443 "POST /app/v2/home_page/get_object_list HTTP/1.1" 200 1618
23:44:55 [INFO][WyzeBridge] [API] Fetched [4] cameras
23:44:55 [INFO][WyzeBridge] 💾 Saving 'cameras' to local cache...
23:44:56 [INFO][WyzeBridge] 🎉 Connecting to WyzeCam V4 - Front on 192.168.1.101
23:44:56 [WARNING][WyzeBridge] WARNING: This process (pid=8) is multi-threaded, use of fork() may lead to deadlocks in the child.
[front] Connect via IOTC_Connect_ByUIDEx
23:44:56 [DEBUG][front] Connect via IOTC_Connect_ByUIDEx
23:45:02 [INFO][WyzeBridge] 172.30.32.2 - - [19/May/2024 23:45:02] "GET / HTTP/1.1" 200 -
23:45:02 [INFO][WyzeBridge] 172.30.32.2 - - [19/May/2024 23:45:02] "GET /static/bulma.css HTTP/1.1" 304 -
23:45:02 [INFO][WyzeBridge] 172.30.32.2 - - [19/May/2024 23:45:02] "GET /static/site.js HTTP/1.1" 304 -
23:45:02 [INFO][WyzeBridge] 172.30.32.2 - - [19/May/2024 23:45:02] "GET /static/bulma-toast.js HTTP/1.1" 304 -
23:45:02 [INFO][WyzeBridge] 172.30.32.2 - - [19/May/2024 23:45:02] "GET /static/site.css HTTP/1.1" 304 -
23:45:02 [INFO][WyzeBridge] 172.30.32.2 - - [19/May/2024 23:45:02] "GET /api/sse_status HTTP/1.1" 200 -
23:45:16 [WARNING][WyzeBridge] ⏰ Timed out connecting to Front.
23:45:17 [INFO][WyzeBridge] 🎉 Connecting to WyzeCam V4 - Front on 192.168.1.101
23:45:17 [WARNING][WyzeBridge] WARNING: This process (pid=8) is multi-threaded, use of fork() may lead to deadlocks in the child.
[front] Connect via IOTC_Connect_ByUIDEx
23:45:17 [DEBUG][front] Connect via IOTC_Connect_ByUIDEx
23:45:37 [WARNING][front] [-13] IOTC_ER_TIMEOUT
23:45:38 [INFO][WyzeBridge] 🎉 Connecting to WyzeCam V4 - Front on 192.168.1.101
23:45:38 [WARNING][WyzeBridge] WARNING: This process (pid=8) is multi-threaded, use of fork() may lead to deadlocks in the child.
[front] Connect via IOTC_Connect_ByUIDEx
23:45:38 [DEBUG][front] Connect via IOTC_Connect_ByUIDEx
23:45:58 [WARNING][front] [-13] IOTC_ER_TIMEOUT
23:45:59 [INFO][WyzeBridge] 🎉 Connecting to WyzeCam V4 - Front on 192.168.1.101
23:45:59 [WARNING][WyzeBridge] WARNING: This process (pid=8) is multi-threaded, use of fork() may lead to deadlocks in the child.
[front] Connect via IOTC_Connect_ByUIDEx
23:45:59 [DEBUG][front] Connect via IOTC_Connect_ByUIDEx

I use one V4 camera and three V3 cameras. The V4 camera is online, but the V3 cameras are offline because they are not powered on.

In this situation, the V4 camera can connect with the Wyze bridge, but there is some connection issue.

Could you help me?

I have tried both P2P mode and ANY mode.

My camera and Wyze bridge are connected to different networks.

It is normal for the V3 cameras to show as offline in the Wyze bridge since they are not powered on.

Even when I power on the V3 cameras, they show the same error message as the V4 camera.

The firmware version of the V4 camera is 4.52.3.9455, and the firmware version of the V3 cameras is 4.36.11.8391.

## Environment  (if applicable)
- Affected Camera(s): WyzeCam V3, V4
- Affected Camera Firmware: 4.52.3.9455
- Affected Bridge Version: 2.9.2
- Bridge type:
  - [ ] Docker Compose/Docker Run
  - [V ] Home Assistant
  - [ ] Other

**Comment by mrlt8** [comment]
No, you'd normally get the `IOTC_ER_DEVICE_OFFLINE` message if the camera is "off" or in privacy mode. 

Unfortunately, there seems to be some kind of NAT punching bug with the latest camera firmware that prevents non-local connections. The only solution right now is to either downgrade the camera or put the bridge on the same network via VPN.

Is the V4 on the same LAN? We may have to extend the connection timeout if it is.

**Comment by tam1230** [comment]
Can i get the V4 and V3 camera version that i can use ?
I will downgrade the camera version and retest it.
no, V4 and V3 camaera are not same network.

**Comment by mrlt8** [comment]
I believe 4.36.11.7095 should work for the v3:
```
https://download.wyzecam.com/firmware/v3/demo_wcv3_4.36.11.7095.bin.zip
```

I don't think there is an older version for the v4.

**Comment by bobloadmire** [comment]
> The only solution right now is to either downgrade the camera or put the bridge on the same network via VPN.

Can you explain a little more so we can impliment this? I'm running OPNsense so I think I should have the tools to do this.

**Comment by mrlt8** [comment]
here's an example using open vpn:
```yaml
services:
  openvpn:
    image: dperson/openvpn-client
    restart: unless-stopped
    ports:
      - 8554:8554 # RTSP
      - 8889:8889 #WebRTC
      - 8189:8189/udp # WebRTC/ICE
      - 5050:5000 # WEB-UI 
    cap_add: [NET_ADMIN]
    command: "-f /vpn/config.ovpn"
    volumes:
      - ./config.ovpn:/vpn/config.ovpn
  wyze-bridge:
    depends_on:
      - openvpn
    network_mode: service:openvpn
    container_name: wyze-bridge
    image: mrlt8/wyze-bridge:latest
    restart: always
    environment:
     ... same as before
```

**Comment by mrlt8** [comment]
@tam1230  Can you ping devices on the `192.168.0.0` network?

**Comment by dmvinson** [comment]
Hi @mrlt8, I'm running into this issue as well with NAT traversal on a V4 camera. I need to run the bridge in the cloud since I plan on accessing cameras on multiple networks. Do you know of any ways to avoid configuring port forwarding for each router I plan on using with V4 cameras?

**Comment by mrlt8** [comment]
Have you looked into Tailscale? You'd need to have a subnet router on each different network (something like an appletv would work), and you could run the container anywhere as long as it's connected to the tailscale network:

```yaml
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: wyze-bridge # For tailscale
    restart: unless-stopped
    cap_add: [NET_ADMIN]
    environment:
      - TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
      - TS_EXTRA_ARGS=--accept-routes
      - TS_USERSPACE=false
    volumes:
      - /dev/net/tun:/dev/net/tun
  wyze-bridge:
    container_name: wyze-bridge
    restart: unless-stopped
    image: mrlt8/wyze-bridge:latest
    depends_on: [tailscale]
    network_mode: service:tailscale
    environment:
....
```
