### ISSUE TITLE
WebRTC 404, SetRemoteDescription called with no ice-ufrag

### ISSUE THREAD

**Issue by bpmich** [mrlt8/docker-wyze-bridge#1230]
## Describe the bug
Provide a clear and concise description of the issue and include logs if applicable.
WebRTC streams are failing to connect in Frigate

Error in Question (produced by Frigate)
`SetRemoteDescription called with no ice-ufrag" stream=alley`

docker-wyze-bridge Docker Compose:
```
version: "2.4"
services:
  wyze-bridge:
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://192.168.1.244:2514"
        syslog-format: "rfc3164"
        tag: "wyze-bridge"
    container_name: wyze-bridge
    restart: unless-stopped
    image: mrlt8/wyze-bridge:latest
    ports:
        - 1936:1935 # RTMP
        - 8556:8554 # RTSP
        - 8888:8888 # HLS
        - 8889:8889 #WebRTC
        - 8189:8189/udp # WebRTC/ICE
        - 5500:5000 # WEB-UI
    environment:
        - WB_AUTH=False
        - WYZE_EMAIL=${WYZE_EMAIL}
        - WYZE_PASSWORD=${WYZE_PASSWORD}
        - API_ID=redacted
        - API_KEY=redacted
        - ROTATE_CAM_ALLEY_CAMERA=2
        - ENABLE_AUDIO=True
        - WB_IP=192.168.1.244
    networks:
      - proxy

networks:
  proxy:
    external: true
```

Relevant docker-wyze-bridge logs:
`[WyzeBridge] 172.18.0.1 - - [26/May/2024 02:15:00] "POST /living-room-camera/ HTTP/1.1" 404 -`

Relevant Frigate config:
```
go2rtc:
  streams:
    alley:
    - webrtc:http://192.168.1.244:8889/alley-camera/
    backyard:
    - webrtc:http://192.168.1.244:8889/backyard-camera/
    living_room:
    - webrtc:http://192.168.1.244:5500/living-room-camera/
  webrtc:
    candidates:
    - 192.168.1.244:8555
    - stun:8555
```

## Environment  (if applicable)
- Affected Camera(s): Wyze Cam v3
- Affected Camera Firmware: 4.36.11.8391
- Affected Bridge Version: 2.9.3
- Bridge type:
  - [x] Docker Compose/Docker Run
  - [ ] Home Assistant
  - [ ] Other

**Comment by bpmich** [comment]
Update, after enabling auth and reconfiguring Frigate, I get a new error from the go2rtc component.

`error="streams: sdp: syntax error at pos 1: \"0\"" stream=living_room`

**Comment by bpmich** [comment]
Looking to see what I can add to help diagnose this issue. Any suggestions?

**Comment by mrlt8** [comment]
Have you tried the RTSP stream?

**Comment by bpmich** [comment]
> Have you tried the RTSP stream?

Yes, I can confirm the RTSP stream is functional. Here is the go2rtc config I have set up in order to test different docker-wyze-bridge env vars:

```
go2rtc:
  streams:
    #alley:
    #  - webrtc:http://192.168.1.244:8889/alley-camera/
    #backyard:
    #  - webrtc:http://192.168.1.244:8889/backyard-camera/
    #living_room:
    #  - webrtc:http://192.168.1.244:8889/signaling/living-room-camera?kvs#format=wyze
    alley:
      - ffmpeg:rtsp://192.168.1.244:8556/alley-camera
      - "ffmpeg:alley#audio=aac"
    backyard:
      - ffmpeg:rtsp://192.168.1.244:8556/backyard-camera
      - "ffmpeg:backyard#audio=aac"
    living_room:
      - ffmpeg:rtsp://192.168.1.244:8556/living-room-camera
      - "ffmpeg:living_room#audio=aac"
  webrtc:
    candidates:
      - 192.168.1.244:8555
      - stun:8555
```

These cameras were working using webrtc prior to the wyze-api update. At that time, I was pointing directly to the docker-wyze-bridge WebUI port to get the WebRTC stream working. The go2rtc config looked like this:

```
go2rtc:
  streams:
    alley:
      - webrtc:http://192.168.1.244:5000/signaling/alley-camera?kvs#format=wyze
    backyard:
      - webrtc:http://192.168.1.244:5000/signaling/backyard-camera?kvs#format=wyze
    living_room:
      - webrtc:http://192.168.1.244:5000/signaling/living-room-camera?kvs#format=wyze
  webrtc:
    candidates:
      - 192.168.1.244:8555
      - stun:8555
```

For posterity, here is my current docker-compose for docker-wyze-bridge

```
version: "2.4"
services:
  wyze-bridge:
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://192.168.1.244:2514"
        syslog-format: "rfc3164"
        tag: "wyze-bridge"
    container_name: wyze-bridge
    restart: unless-stopped
    image: mrlt8/wyze-bridge:latest
    ports:
        - 1936:1935 # RTMP
        - 8556:8554 # RTSP
        - 8888:8888 # HLS
        - 8889:8889 #WebRTC
        - 8189:8189/udp # WebRTC/ICE
        - 5500:5000 # WEB-UI
    environment:
        - WB_AUTH=False
        - WYZE_EMAIL=${WYZE_EMAIL}
        - WYZE_PASSWORD=${WYZE_PASSWORD}
        - API_ID=REDACTED
        - API_KEY=REDACTED
        - ROTATE_CAM_ALLEY_CAMERA=2
        - ENABLE_AUDIO=True
        - ON_DEMAND=false
        - NET_MODE=P2P
        - IGNORE_OFFLINE=true
        - WB_IP=192.168.1.244
        - FILTER_NAMES=Driveway
        - FILTER_BLOCK=true
    networks:
      - proxy

networks:
  proxy:
    external: true
```
