### ISSUE TITLE
As soon as it is deployed, it closes.  (docker)

### ISSUE THREAD

**Issue by azagramac** [mrlt8/docker-wyze-bridge#1239]
## Describe the bug
As soon as it is deployed, it closes. Without being able to continue or configure any camera.

## Environment  (if applicable)
- Affected Camera(s): n/a
- Affected Camera Firmware: n/a
- Affected Bridge Version: v2.9.4
- Bridge type:
  - [X] Docker Compose/Docker Run

## Run
```sh
# docker compose up -d
[+] Running 2/2
 ✔ Network wyze-bridge_default  Created                                                                                                                                                                            0.3s 
 ✔ Container wyze-bridge        Started                                                                                                                                                                            1.9s 
```

## Output log
```sh
# docker logs wyze-bridge -f

🚀 DOCKER-WYZE-BRIDGE v2.9.4 AARCH64

[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.21.0.2:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'user'
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] 💾 Saving 'user' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] [API] Fetched [0] cameras
[WyzeBridge] Stopping 0 streams
[WyzeBridge] 👋 goodbye!
```

## Docker compose code
```yml
services:
  wyze-bridge:
    image: mrlt8/wyze-bridge:latest
    container_name: wyze-bridge
    restart: unless-stopped
    environment:
      - WYZE_EMAIL=MY_MAIL
      - WYZE_PASSWORD=MY_PASS
      - API_ID=XXXXXXXXXXXXXXXXXXX
      - API_KEY=XXXXXXXXXXXXXXXXXXX
      - WB_AUTH=False
    ports:
      - 1935:1935
      - 8554:8554
      - 8888:8888
      - 8889:8889
      - 8189:8189/udp
      - 5000:5000
```
