### ISSUE TITLE
Expose rtsp-simple-server metrics

### ISSUE THREAD

**Issue by Alfiegerner** [mrlt8/docker-wyze-bridge#124]
Hi,

I'd like to be able to poll rtsp-simple-server metrics to check for camera failure, so mapped 9998 as follows:

```
  wyze-bridge:
        container_name: wyze-bridge
        restart: always
        ports:
            - 1936:1935
            - 8554:8554
            - 8888:8888
            - 9998:9998
        environment:
            - WYZE_EMAIL=
            - WYZE_PASSWORD=
            - LAN_ONLY=True
            - QUALITY=HD120
            - RTSP_RTMPDISABLE=yes
```
But there's nothing coming through on that port.  Any ideas?

Interesting I made this change hoping to debug why 2 cameras had stopped (first seen not streaming in Frigate, then checked in wyze app and both cams not responding). On deploying this change and restarting wyze-bridge both cams became available again in app and Frigate.

The core problem I'm trying to work around is that sometimes the cams 'freeze' or become unavailable without fps being affected, and I'm trying to determine when that happens so I can automate the restarting of cams, wyze-bridge etc.  For whatever reason sometimes when cams become unavailable in wyze app rtsp-simple-server continues to stream what look like a valid rtsp stream in terms of fps, so can not detect using ffprobe or upstream processing stats, e.g. from Frigate.
