### ISSUE TITLE
RTSP_THUMB - which port to use?

### ISSUE THREAD

**Issue by parthmodi** [mrlt8/docker-wyze-bridge#125]
Hi, I want to use the RTSP_Thumb with home assistant, but my wyze bridge docker and home assitant are on two different machines. What port should I use to send over the still image?

**Comment by mrlt8** [comment]
The container doesn't have an http server, but the images should be in `/img/`. 
You could use something like nginx in your docker-compose and share the /img/ folder between the services with a volume or something like this:
```yaml
services:
  wyze-bridge:
...
    volumes:
      - ./img:/img
  web:
    container_name: nginx
    image: nginx:mainline-alpine
    ports:
        - 8080:80
    volumes:
        - ./img:/usr/share/nginx/html
```
