### ISSUE TITLE
Audio Not Working on latest-hw Tag

### ISSUE THREAD

**Issue by hevel86** [mrlt8/docker-wyze-bridge#1281]
## Describe the bug

Audio does not work when using the `latest-hw` tag in docker-compose.  I do have the option to toggle the icon off or on, but no audio is heard.  Moving to the `latest` tag resumes audio.

## Environment  (if applicable)
- Affected Camera(s):
  - Wyze Cam Pan
- Affected Camera Firmware:
  - 4.10.9.3006
- Affected Bridge Version:
  - 2.9.10
- Bridge type:
  - [x] Docker Compose/Docker Run
  - [ ] Home Assistant
  - [ ] Other

## Working Non-HW Docker Compose

```
wyze_bridge:
    #image: mrlt8/wyze-bridge:latest-hw
    image: mrlt8/wyze-bridge:latest
    privileged: true
    container_name: wyze_bridge
    restart: unless-stopped
    environment:
      - WB_AUTH=false
      - WB_IP=$WB_IP
      - WYZE_EMAIL=$WYZE_EMAIL
      - WYZE_PASSWORD=$WYZE_PASSWORD
      - API_KEY=$API_KEY
      - API_ID=$API_ID
      - QUALITY_OFFICE_CAM=HD120
      #- TOTP_KEY=$TOTP_KEY
      - ROTATE_DOOR=true
      #- H264_ENC=h264_nvenc
      - NET_MODE=LAN
      - ENABLE_AUDIO=true
      #- NVIDIA_VISIBLE_DEVICES=all
      #- NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    ports:
      - 1935:1935
      - 8556:8554 #conflicted with frigate
      - 8888:8888
      - 8889:8889 #webrtc
      - 8189:8189/udp #webrtc/ICE
      - 5001:5000
    devices:
      - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
```

## No Audio HW Docker Compose

```
wyze_bridge:
    image: mrlt8/wyze-bridge:latest-hw
    privileged: true
    container_name: wyze_bridge
    restart: unless-stopped
    environment:
      - WB_AUTH=false
      - WB_IP=$WB_IP
      - WYZE_EMAIL=$WYZE_EMAIL
      - WYZE_PASSWORD=$WYZE_PASSWORD
      - API_KEY=$API_KEY
      - API_ID=$API_ID
      - QUALITY_OFFICE_CAM=HD120
      #- TOTP_KEY=$TOTP_KEY
      - ROTATE_DOOR=true
      - H264_ENC=h264_nvenc
      - NET_MODE=LAN
      - ENABLE_AUDIO=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    ports:
      - 1935:1935
      - 8556:8554 #conflicted with frigate
      - 8888:8888
      - 8889:8889 #webrtc
      - 8189:8189/udp #webrtc/ICE
      - 5001:5000
    devices:
      - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
```
