### ISSUE TITLE
BUG: Unable to login after pulling latest version

### ISSUE THREAD

**Issue by rtfclb8** [mrlt8/docker-wyze-bridge#1306]
### Describe the bug

Running in a docker container.
docker-compose.yml file contains my USERNAME/PASSWORD as well as API ID/API KEY
After upgrading, I go to 192.168.1.249:5000 and get a login pop up. I enter my wyze username & password, hit enter, and nothing. The pop up just stays there. I read through the changes, and it seems like I should be good to go (like all the previous updates) but no dice. If I restore from backup, it goes back to working fine version 2.9.10. I have tried removing my username/pw from the .yml file as well as the API info. When I do that, I can get to the login web page, but when I fill in everything, it goes back to the pop up login window.

### Affected Bridge Version

2.10.1

### Bridge type

Docker Run/Compose

### docker-compose or config (if applicable)

```yaml
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            - WYZE_EMAIL=myemail@hotmail.com
            - WYZE_PASSWORD=mypassword
            - API_ID=my API_ID
            - API_KEY=my API_KEY
            - WB_IP=192.168.1.249
```
