### ISSUE TITLE
BUG: Latest version cannot stay connected to my Wyze V3 cameras but 2.9.12 and previous work fine

### ISSUE THREAD

**Issue by RyanEwen** [mrlt8/docker-wyze-bridge#1315]
### Describe the bug

After updating to 2.10.1 I cannot seem to get video streams (using the web ui) to start or remain started if a stream or two does happen to start. The logs don't show any errors - just client disconnecting and connecting.

Downgrading to 2.9.12 solves the issue and all 6 cameras work smoothly again via WebRTC & HLS.

### Affected Bridge Version

v2.10.1

### Bridge type

Docker Run/Compose

### Affected Camera(s)

Wyze V3

### Affected Camera Firmware

latest

### docker-compose or config (if applicable)

```yaml
wyze-bridge:
    image: mrlt8/wyze-bridge:latest
    network_mode: host
    environment:
      - WYZE_EMAIL=xxx@gmail.com
      - WYZE_PASSWORD=xxx
      - API_ID=xxx
      - API_KEY=xxx
      - NET_MODE=LAN
      - WB_AUTH=false
      - WB_IP=192.168.2.10
    restart: unless-stopped
```
```
