### ISSUE TITLE
BUG: Playback Issues 

### ISSUE THREAD

**Issue by g-stick** [mrlt8/docker-wyze-bridge#1319]
### Describe the bug

When attempting to playback on windows, the media player fails  to play the audio, there's a pop up saying "we can't play the audio for xxxx-xx-xx_xx-xx-xx. It's encoded in ipcm format which isn't supported. You can still watch the video".
The video plays however I am unable to seek forward or backwards.

When I try to use VLC media player, it takes some time to "parse the file" before playback begins. It is able to play the video and audio, and seek works, h
![ipcm](https://github.com/user-attachments/assets/f7231010-b38a-4174-8527-05d2030773ff)
owever it is not very responsive.

### Affected Bridge Version

v2.10.1

### Bridge type

Docker Run/Compose

### docker-compose or config (if applicable)

```yaml
wyze-bridge:
    <<: *common-keys-core
    container_name: wyze-bridge
    restart: unless-stopped
    image: mrlt8/wyze-bridge:latest
    ports:
      - 1935:1935 # RTMP
      - 8554:8554 # RTSP
      - 8888:8888 # HLS
      - 8889:8889 #WebRTC
      - 8189:8189/udp # WebRTC/ICE
      - 5000:5000 # WEB-UI
    environment:
      <<: *default-tz-puid-pgid
      # [OPTIONAL] (Can be set in the WebUI):
      WYZE_EMAIL: $WYZE_EMAIL
      WYZE_PASSWORD: $WYZE_PASSWORD
      API_ID: $WYZE_KEY_ID
      API_KEY: $WYZE_API_KEY
      WB_IP: 192.168.2.115
      ENABLE_AUDIO: True
      RECORD_ALL: True
      RECORD_LENGTH: 300s
#      RECORD_KEEP: 672h
    volumes:
      - $VAULT/record:/record/
```
