### ISSUE TITLE
BUG: [v3 cam]  Wyze-bridge no longer works with newer firmware

### ISSUE THREAD

**Issue by rakbladsvalsen** [mrlt8/docker-wyze-bridge#1325]
### Describe the bug

Hey, just as the title suggests, looks like Wyze Inc. killed the bridge with the latest firmware update for the v3 cameras. I don't know if this is also the case for the other models, but as far as the regular v3 goes it no longer works.

I already tried the following:

- [x] Use  a different NET_MODE mode (p2p/lan)
- [x] Try the latest `:edge` builds
- [x] Use static IP addresses for the cameras
- [x] Rule out possible router issues 
- [x] Use nmap to verify whether the IP discovered by WyzeBridge is valid (and yes, it is)

I know something is definitely up because wyze-bridge does work with the old FW. I have multiple v3 cameras and I tried updating just one of them and surprise surprise, the new fw magically breaks the bridge. The phone app is still working fine as usual. 

```
WyzeBridge] 🔍 Could not find local cache for 'user'
[WyzeBridge] ☁ Fetching 'user' from the Wyze API...
[WyzeBridge] 💾 Saving 'user' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] ☁ Fetching 'cameras' from the Wyze API...
[WyzeBridge] [API] Fetched [3] cameras
[WyzeBridge] 💾 Saving 'cameras' to local cache...
< snip >
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - right on 192.168.68.63
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - left on 192.168.68.64
[right] [-13] IOTC_ER_TIMEOUT
[left] [-13] IOTC_ER_TIMEOUT
<... repeats over and over ...> 
```

I believe this might be a duplicate of https://github.com/mrlt8/docker-wyze-bridge/issues/1298, except this affects the v3 series cameras and everything is broken, regardless of the network access mode. 

### Affected Bridge Version

v2.10.1 X86_64

### Bridge type

Docker Run/Compose

### Affected Camera(s)

v3

### Affected Camera Firmware

4.36.13.0416

### docker-compose or config (if applicable)

```yaml
wyze:
    image: mrlt8/wyze-bridge
    container_name: wyze
    restart: always
    environment:
      - RECORD_ALL=True
      - FRESH_DATA=True
      - WYZE_EMAIL=REDACTED
      - WYZE_PASSWORD=REDACTED
      - API_ID=REDACTED
      - API_KEY=REDACTED
      - MTX_READTIMEOUT=10s
      - ON_DEMAND=False   
      - ENABLE_AUDIO=True
      - RECORD_LENGTH=60s
    volumes:
      - ... <local path>
    ports:
      - ... <some IP>
```
