### ISSUE TITLE
BUG: short recording times and lots of disconnects

### ISSUE THREAD

**Issue by tabooki** [mrlt8/docker-wyze-bridge#1333]
### Describe the bug

I keep getting disconnects and 10 minute uploads when streaming. Running latest updated today. 

Any ideas on what to try? 

down
[WyzeBridge] ✅  '/cat-cam stream is UP! (3/3)
[WyzeBridge] ✅  '/cat-cam stream is UP! (3/3)
[WyzeBridge] ❌  '/cat-cam' stream is down
[WyzeBridge] ❌  '/cat-cam' stream is down
[WyzeBridge] ✅  '/cat-cam stream is UP! (3/3)
[WyzeBridge] ❌  '/cat-cam' stream is down
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[WyzeBridge] ✅  '/cat-cam stream is UP! (3/3)
[WyzeBridge] ❌  '/cat-cam' stream is down
[WyzeBridge] ✅  '/cat-cam stream is UP! (3/3)
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[cat-cam]  Getting 120kb/s HD stream (H264/20fps) via LAN mode (WiFi: 78%) FW: 4.36.
13.0416
[cat-cam]  Custom (rtmp://live.restream.io/live/re_8013929_debXXXdac1b8081f16ec) liv
estream enabled
[cat-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
[WyzeBridge] ❌  '/cat-cam' stream is down
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[WyzeBridge] ✅  '/cat-cam stream is UP! (3/3)
[WyzeBridge] ❌  '/cat-cam' stream is down
[WyzeBridge] ✅  '/cat-cam stream is UP! (3/3)
[WyzeBridge] ❌  '/cat-cam' stream is down
[WyzeBridge] ✅  '/cat-cam stream is UP! (3/3)
[WyzeBridge] ❌  '/cat-cam' stream is down
[WyzeBridge] ✅  '/cat-cam stream is UP! (3/3)
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[cat-cam] [-48] IOTC_ER_DEVICE_EXCEED_MAX_SESSION
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[cat-cam] [-48] IOTC_ER_DEVICE_EXCEED_MAX_SESSION
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[cat-cam]  Getting 120kb/s HD stream (H264/20fps) via LAN mode (WiFi: 73%) FW: 4.36.
13.0416
[cat-cam]  Custom (rtmp://live.restream.io/live/re_8013929_debd7XXXc1b8081f16ec) liv
estream enabled
[cat-cam] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
[WyzeBridge] ✅  '/cat-cam stream is UP! (3/3)
[WyzeBridge] ❌  '/cat-cam' stream is down
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[cat-cam] [-48] IOTC_ER_DEVICE_EXCEED_MAX_SESSION
[WyzeBridge] ❌  '/cat-cam' stream is down
[WyzeBridge] ✅  '/cat-cam stream is UP! (3/3)
[WyzeBridge] ❌  '/cat-cam' stream is down
[WyzeBridge] ✅  '/cat-cam stream is UP! (3/3)
[WyzeBridge] ❌  '/cat-cam' stream is down
[WyzeBridge] ✅  '/cat-cam stream is UP! (3/3)
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[cat-cam] [-48] IOTC_ER_DEVICE_EXCEED_MAX_SESSION
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[cat-cam] [-48] IOTC_ER_DEVICE_EXCEED_MAX_SESSION
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[cat-cam] [-48] IOTC_ER_DEVICE_EXCEED_MAX_SESSION
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[cat-cam] [-48] IOTC_ER_DEVICE_EXCEED_MAX_SESSION
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[cat-cam] [-48] IOTC_ER_DEVICE_EXCEED_MAX_SESSION
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[cat-cam] [-48] IOTC_ER_DEVICE_EXCEED_MAX_SESSION
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[cat-cam] [-48] IOTC_ER_DEVICE_EXCEED_MAX_SESSION
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[cat-cam] [-48] IOTC_ER_DEVICE_EXCEED_MAX_SESSION
[WyzeBridge]  Connecting to WyzeCam V3 - Cat Cam on 10.0.0.159
[cat-cam]  Getting 120kb/s HD stream (H264/20fps) via LAN mode (WiFi: 50%) FW: 4.36.
13.0416
[cat-cam]  Custom (rtmp://live.restream.io/live/re_8013929_debdXxxac1b8081f16ec) liv
estream enabled

### Affected Bridge Version

V2.10.2

### Bridge type

Docker Run/Compose

### docker-compose or config (if applicable)

```yaml
version: '2.9'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
      #  image: mrlt8/wyze-bridge:edge
        image: mrlt8/wyze-bridge:latest
        #image: mrlt8/wyze-bridge:dev

        ports:
            - 10.0.0.1:1935:1935 # RTMP
            - 10.0.0.1:8554:8554 # RTSP
            - 10.0.0.1:8888:8888 # HLS
            - 10.0.0.1:8889:8889 #WebRTC
            - 10.0.0.1:8189:8189/udp # WebRTC/ICE
            - 10.0.0.1:5000:5000 # WEB-UI
       # mem_limit: 2048m
        cpus: "1.0"
          
        environment:

            - WB_USERNAME=xxx
            - WB_PASSWORD=xxx
            #- WB_AUTH=false

#ENABLE_AUDIO=false
            # [OPTIONAL] Credentials can be set in the WebUI
            # API Key and ID can be obtained from the wyze dev portal: 
            # https://developer-api-console.wyze.com/#/apikey/view
            - WYZE_EMAIL=xxx@gmail.com
            - WYZE_PASSWORD=xxx
            - API_ID=xxx
            - API_KEY=xcx
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            # - WB_IP=192.168.1.122
            #
            # get rid of keyframe error
            #- IGNORE_RES=1
            #Set Quality 
            #- QUALITY=SD60
            - QUALITY=HD120         # Setting high quality for the stream
            - BITRATE=6500k         # Adjust bitrate as needed, higher bitrate for better quality
          #  - RESOLUTION=1920x1080  # Set resolution to 1080p for HD streaming
            - RESOLUTION=1280x720   # Setting the resolution to 1280x720
            #- FRAMESIZE=1920x1080

            #- FORCE_FPS_CATCAM=15
            
            # Testing Persistent Connection option for disconnects
            # https://github.com/mrlt8/docker-wyze-bridge/wiki/Advanced-Option#persistent-connection
            - ON_DEMAND=False
            
            # Filter out the cams not needed. only allow listed
            - FILTER_NAMES=Cat Cam
            
            #Enable streaming to restream or youtube
            #
            - LIVESTREAM_CAT_CAM=rtmp://live.restream.io/live/xXx

            #- LIVESTREAM_CAT_CAM=rtmp://a.rtmp.youtube.com/live2/xXX


            #- YOUTUBE_CAT_CAM=rtmp://a.rtmp.youtube.com/live2/xXX
```
