### ISSUE TITLE
BUG: V4 audio

### ISSUE THREAD

**Issue by primate-star** [mrlt8/docker-wyze-bridge#1341]
### Describe the bug

I have two V4 and another Pan Cam connected to homekit via wyze-home-bridge and scrypted on same local network. The live and recorded video is working well and the audio on V4's works well as well on starting the container. However after about an hour there is no audio on V4's. If I restart the container, audio again works for sometime and then it stops but video keeps on going. The Pan Cam audio remains unaffected. I have checked the logs and it indicates audio is enabled and on when container starts. The logs don't indicate audio has stopped when I hear no audio. I have tried enabling audio en masse or individually for cameras in the docker compose and the effect is same. The audio on wyze app itself works fine. The audio issue replicates when I check rtsp streams in VLC player for the V4's.
Appreciate mrlt8's and other contributors work on this bridge immensely

### Affected Bridge Version

2.10.2

### Bridge type

Docker Run/Compose

### Affected Camera(s)

V4

### Affected Camera Firmware

4.52.7.0367

### docker-compose or config (if applicable)

```yaml
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            # [OPTIONAL] Credentials can be set in the WebUI
            # API Key and ID can be obtained from the wyze dev portal: 
            # https://developer-api-console.wyze.com/#/apikey/view
            - WYZE_EMAIL=sample
            - WYZE_PASSWORD=sample
            - API_ID=sample
            - API_KEY=sample
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            - WB_IP=172.16.0.100
            # WebUI and Stream authentication:
            - WB_AUTH=True # Set to false to disable web and stream auth.
            # WB_USERNAME=sample
            # WB_PASSWORD=sample
            - QUALITY=HD180
            - ENABLE_AUDIO=True
            - AUDIO_CODEC=AAC
            - AUDIO_FILTER=highpass=f=300,lowpass=f=2500,volume=volume=2
```
