### ISSUE TITLE
Help Wanted for HomeBridge

### ISSUE THREAD

**Issue by airbornetrooper82573** [mrlt8/docker-wyze-bridge#136]
I am unable to get my v3 camera to load. I have the proper firmware loaded but it will not stream in HomeKit. RTSP works fine in VLC though. I have docker setup on a Pi that also hosts Pi-hole and HomeBridge runs on my TrueNAS server.  Here are my configs, I hope someone can help me please. 

docker-compose.yml:
```
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: always
        image: mrlt8/wyze-bridge:latest # Use a prebuilt image
        # build:  # Uncomment to build from source
        #     context: ./app # Uncomment to build from source
        #     # dockerfile: Dockerfile.arm # Uncomment to build for arm
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
        environment:
            - WYZE_EMAIL=myemail@gmail.com # Replace with wyze email
            - WYZE_PASSWORD=mypassword # Replace with wyze password
            - FFMPEG_CMD=-f h264 -i - -vcodec copy -f flv rtmp://172.16.1.48:1935/
            - RTSP_PATHS_ALL_READUSER=123
            - RTSP_PATHS_ALL_READPASS=asd
```
Homebridge Camera FFmpeg config
```
{
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Front Yard Cam",
                    "manufacturer": "Wyze",
                    "model": "V3",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport http -re -i rtsp://123:asd@172.16.1.48:8554/front-yard-cam",
                        "maxStreams": 2,
                        "maxWidth": 1024,
                        "maxHeight": 576,
                        "maxFPS": 15,
                        "vcodec": "copy",
                        "mapvideo": "0:1",
                        "mapaudio": "0:0",
                        "audio": true,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```

**Comment by noelhibbard** [comment]
If I recall I could only get mine to work with transcoding. ```"vcodec": "libx264"```

**Comment by airbornetrooper82573** [comment]
> If I recall I could only get mine to work with transcoding. `"vcodec": "libx264"`

Made the change and still nothing

**Comment by airbornetrooper82573** [comment]
Here is the only thing I see in Homebridge logs:

```
[9/20/2021, 12:42:35 PM] [Camera FFmpeg] [Front Yard Cam] Snapshot command: ffmpeg -rtsp_transport http -re -i rtsp://123:asd@172.16.1.48:8554/front-yard-cam -frames:v 1 -f image2 - -hide_banner -loglevel error
[9/20/2021, 12:42:35 PM] [Camera FFmpeg] [Front Yard Cam] Fetching snapshot took 0.015 seconds.
[9/20/2021, 12:42:37 PM] [Camera FFmpeg] [Front Yard Cam] Snapshot requested: 1280 x 720
```

**Comment by airbornetrooper82573** [comment]
Here are the Homebridge logs when I try to start the camera in HomeKit:

```
[9/20/2021, 1:07:36 PM] [Camera FFmpeg] [Front Yard Cam] Video stream requested: 1280 x 720, 30 fps, 299 kbps
[9/20/2021, 1:07:36 PM] [Camera FFmpeg] [Front Yard Cam] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[9/20/2021, 1:07:36 PM] [Camera FFmpeg] [Front Yard Cam] Stream command: ffmpeg -rtsp_transport http -re -i rtsp://123:asd@172.16.1.48:8554/front-yard-cam -map 0:1 -codec:v copy -pix_fmt yuv420p -color_range mpeg -f rawvideo -payload_type 99 -ssrc 5664837 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params qUPD7kO2b8IZaVWkAjd2WLszICLMqJGRJoqgZJOg srtp://172.16.1.159:60938?rtcpport=60938&pkt_size=1316 -map 0:0 -codec:a libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -ac 1 -payload_type 110 -ssrc 1295844 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params TH9sfx4BIlfqUOf0aW4dt5j3IRmmTgRSWAT0bCcw srtp://172.16.1.159:55171?rtcpport=55171&pkt_size=188 -loglevel level+verbose -progress pipe:1
[9/20/2021, 1:07:36 PM] [Camera FFmpeg] [Front Yard Cam] Stopped video stream.
```

**Comment by noelhibbard** [comment]
I will resurrect my V3 when I get home tonight and then report back exactly what settings work for me.

**Comment by mrlt8** [comment]
Shouldn't need anything too fancy. Try this in your videoConfig:
```yaml
"videoConfig": {
    "source": "-i rtsp://123:asd@172.16.1.48:8554/front-yard-cam",
    "vcodec": "copy"
}
```

btw, any reason for using the custom ffmpeg command in the bridge?

**Comment by noelhibbard** [comment]
Something like this worked for me. I am not using the FFMPEG_CMD environment variable in my docker-compose though.

```json
{
    "name": "Front Yard Cam",
    "unbridge": true,
    "videoConfig": {
        "source": "-fflags nobuffer -i rtsp://123:asd@172.16.1.48:8554/front-yard-cam",
        "maxWidth": 1920,
        "maxHeight": 1080,
        "maxFPS": 20,
        "vcodec": "copy",
        "audio": false,
        "debug": false
    }
}
```

**Comment by airbornetrooper82573** [comment]
I tried with the removed custom ffmpeg command. I've also tried with simple videoConfig and the one @noelhibbard recommended. I'm still unable to get the stream to play in HomeKit.

**Comment by airbornetrooper82573** [comment]
wye-bridge log:

wyze-bridge    | 2021/09/21 23:02:45 [Front Yard Cam] 🎉 Starting 1080p 120kb/s Stream for WyzeCam V3 in "LAN mode" FW: 4.36.3.19 IP: 172.16.1.167 WiFi: 92%
wyze-bridge    | ffmpeg version N-58594-g715f63232f-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
wyze-bridge    |   built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
wyze-bridge    |   configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libxml2 --enable-libxvid --enable-libzimg
wyze-bridge    |   libavutil      57.  5.100 / 57.  5.100
wyze-bridge    |   libavcodec     59.  7.103 / 59.  7.103
wyze-bridge    |   libavformat    59.  5.100 / 59.  5.100
wyze-bridge    |   libavdevice    59.  0.101 / 59.  0.101
wyze-bridge    |   libavfilter     8.  7.101 /  8.  7.101
wyze-bridge    |   libswscale      6.  1.100 /  6.  1.100
wyze-bridge    |   libswresample   4.  0.100 /  4.  0.100
wyze-bridge    |   libpostproc    56.  0.100 / 56.  0.100
wyze-bridge    | Unrecognized option 'F'.
wyze-bridge    | Error splitting the argument list: Option not found
wyze-bridge    | 2021/09/21 23:02:45 [Front Yard Cam] [FFMPEG] [Errno 32] Broken pipe

**Comment by mrlt8** [comment]
Can the pi access the NAS?

Also make sure to comment out the entire FFMPEG_CMD line or it may try to process it as a blank command.

**Comment by airbornetrooper82573** [comment]
The Pi can ping my NAS. I'm not familiar enough with docker to know if I need to go in and make some changes to the settings. I see a docker interface when I run the ifconfig command. My Pi and NAS are on the same subnet though. The Pi's main use is for pi-hole.

**Comment by mrlt8** [comment]
Docker should be fine as is since you're able to stream to VLC.

You could try to curl the HLS page from the NAS where homebridge is installed to rule out any network issues:
```
curl -X GET -I http://123:asd@172.16.1.48:8888/front-yard-cam/
```

**Comment by mrlt8** [comment]
Wait, `172.16.1.48` is the IP address of your Pi right?

**Comment by airbornetrooper82573** [comment]
> Docker should be fine as is since you're able to stream to VLC.
> 
> You could try to curl the HLS page from the NAS where homebridge is installed to rule out any network issues:
> 
> ```
> curl -X GET -I http://123:asd@172.16.1.48:8888/front-yard-cam/
> ```

root@truenas[~]# curl -X GET -I http://123:asd@172.16.1.48:8888/front-yard-cam/
HTTP/1.1 404 Not Found
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Date: Wed, 22 Sep 2021 13:53:14 GMT
Content-Length: 0

**Comment by airbornetrooper82573** [comment]
> Wait, `172.16.1.48` is the IP address of your Pi right?

yes, 48 is my pi address. Homebridge runs on 172.16.1.239

**Comment by airbornetrooper82573** [comment]
> Docker should be fine as is since you're able to stream to VLC.
> 
> You could try to curl the HLS page from the NAS where homebridge is installed to rule out any network issues:
> 
> ```
> curl -X GET -I http://123:asd@172.16.1.48:8888/front-yard-cam/
> ```

root@truenas[~]# curl -X GET -I http://123:asd@172.16.1.48:8888/front-yard-cam/

HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Date: Wed, 22 Sep 2021 14:08:26 GMT
Content-Length: 1044
Content-Type: text/html; charset=utf-8

I can view that in my browser. I'm thinking the issue must be somewhere in my Homebridge config then. 

Here's my current docker-compose.yml so we are on the same page and I won't change things until I hear back
```
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: always
        image: mrlt8/wyze-bridge:latest # Use a prebuilt image
        # build:  # Uncomment to build from source
        #     context: ./app # Uncomment to build from source
        #     # dockerfile: Dockerfile.arm # Uncomment to build for arm
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
        environment:
            - WYZE_EMAIL=myemail@gmail.com # Replace with wyze email
            - WYZE_PASSWORD=mypassword # Replace with wyze password
            - FFMPEG_CMD=-f h264 -i - -vcodec copy -f flv rtmp://172.16.1.48:1935/
            - RTSP_LOGLEVEL=debug
            - RTSP_PATHS_ALL_READUSER=123
            - RTSP_PATHS_ALL_READPASS=asd
```
HomeBridge Config:
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Front Yard Cam",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://123:asd@172.16.1.48:1935/front-yard-cam",
                        "vcodec": "copy"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"

Here is the Homebridge log when I open the camera in HomeKit on my iPhone:

[9/22/2021, 10:14:22 AM] [Camera FFmpeg] [Front Yard Cam] Video stream requested: 1280 x 720, 30 fps, 299 kbps
[9/22/2021, 10:14:22 AM] [Camera FFmpeg] [Front Yard Cam] Starting video stream: native x native, native fps, ??? kbps
[9/22/2021, 10:14:22 AM] [Camera FFmpeg] [Front Yard Cam] Stream command: ffmpeg -i rtsp://123:asd@172.16.1.48:8554/front-yard-cam -an -sn -dn -codec:v copy -pix_fmt yuv420p -color_range mpeg -f rawvideo -payload_type 99 -ssrc 12224553 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params tHxzYFEn2RWbmCTD+I5aA+RX6ae/nrALSSb3wVT6 srtp://172.16.1.159:56233?rtcpport=56233&pkt_size=1316 -loglevel level -progress pipe:1
[9/22/2021, 10:14:22 AM] [Camera FFmpeg] [Front Yard Cam] Stopped video stream.
