### ISSUE TITLE
Cannot connect to WyzeCam V2 since September 27

### ISSUE THREAD

**Issue by alexplatform** [mrlt8/docker-wyze-bridge#1367]
Something changed(?) last week and for the life of me I cant get video from my camera. I downgraded to 2.9.12, 2.10.3, and the behavior is always the same-

```
🚀 DOCKER-WYZE-BRIDGE v2.9.12 X86_64

[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.21.0.2:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'user'
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] 💾 Saving 'user' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] [API] Fetched [2] cameras
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] 🪄 FILTER BLOCKING: 1 of 2 cams
[WyzeBridge] [+] Adding geyser front yard [WYZEC1-JZ]
[WyzeBridge] starting MediaMTX 1.1.1
[WyzeBridge] 🎬 1 stream enabled
[WyzeBridge] 192.168.10.102 - - [02/Oct/2024 22:29:30] "GET /api/sse_status HTTP/1.1" 200 -
[WyzeBridge] 🎉 Connecting to WyzeCam V2 - geyser front yard on 172.31.0.106
[geyser-front-yard] [-13] IOTC_ER_TIMEOUT
[WyzeBridge] 🎉 Connecting to WyzeCam V2 - geyser front yard on 172.31.0.106
[WyzeBridge] 192.168.10.102 - - [02/Oct/2024 22:30:03] "GET / HTTP/1.1" 200 -
[WyzeBridge] 192.168.10.102 - - [02/Oct/2024 22:30:04] "GET /static/site.js HTTP/1.1" 200 -
[WyzeBridge] 192.168.10.102 - - [02/Oct/2024 22:30:04] "GET /static/loading.svg HTTP/1.1" 200 -
[WyzeBridge] 192.168.10.102 - - [02/Oct/2024 22:30:04] "GET /static/bulma.css HTTP/1.1" 200 -
[WyzeBridge] 192.168.10.102 - - [02/Oct/2024 22:30:04] "GET /static/site.css HTTP/1.1" 200 -
[WyzeBridge] 192.168.10.102 - - [02/Oct/2024 22:30:04] "GET /static/bulma-toast.js HTTP/1.1" 200 -
[WyzeBridge] 192.168.10.102 - - [02/Oct/2024 22:30:04] "GET /api/sse_status HTTP/1.1" 200 -
[WyzeBridge] ☁️ Pulling "geyser-front-yard" thumbnail to /img/geyser-front-yard.jpg
[WyzeBridge] ☁️ Pulling "geyser-front-yard" thumbnail to /img/geyser-front-yard.jpg
[WyzeBridge] 192.168.10.102 - - [02/Oct/2024 22:30:05] "GET /img/geyser-front-yard.jpg HTTP/1.1" 200 -
[WyzeBridge] 192.168.10.102 - - [02/Oct/2024 22:30:05] "GET /img/geyser-front-yard.jpg HTTP/1.1" 304 -
[WyzeBridge] 192.168.10.102 - - [02/Oct/2024 22:30:05] "GET /snapshot/geyser-front-yard.jpg?1727908201656 HTTP/1.1" 200 -
[geyser-front-yard] [-13] IOTC_ER_TIMEOUT
[WyzeBridge] 🎉 Connecting to WyzeCam V2 - geyser front yard on 172.31.0.106
[WyzeBridge] 192.168.10.102 - - [02/Oct/2024 22:30:34] "GET /snapshot/geyser-front-yard.jpg?1727908235498 HTTP/1.1" 200 -
[WyzeBridge] [geyser-front-yard] Snapshot timed out
[WyzeBridge] 192.168.10.102 - - [02/Oct/2024 22:30:49] "GET /snapshot/geyser-front-yard.jpg?1727908235498 HTTP/1.1" 304 -
[geyser-front-yard] [-13] IOTC_ER_TIMEOUT
```

the camera thumbnail pulls one dated 9-27 but no current video.

my docker-compose.yml:
```
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:2.9.12
#        volumes:
            #- /config/wyze-bridge/mfa_token.txt:/tokens/totp
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            # [OPTIONAL] (Can be set in the WebUI):
            - WYZE_EMAIL=redacted
            - WYZE_PASSWORD= redacted
#           - TOTP_KEY=redacted
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            # [OPTIONAL] Wyze API credentials:
            - API_ID=redacted
            - API_KEY=redacted
            - WB_AUTH=False
            - FILTER_NAMES=Front Door
            - FILTER_BLOCK=true
```
I tried the same thing with no configuration, but same results.
