### ISSUE TITLE
BUG: {cam_name} doesn't appear to be formatted for webhooks

### ISSUE THREAD

**Issue by traviswparker** [mrlt8/docker-wyze-bridge#1378]
### Describe the bug

The {cam_name} format isn't being parsed when sending a motion webhook. I'm seeing this in the logs for motion events:
```
[WyzeBridge] [MOTION] Motion detected on porch at  17:04:35
[WEBHOOKS] 500 Server Error: Internal Server Error for url: http://localhost:8555/motion?%7Bcam_name%7D
[WyzeBridge] ☁️ Pulling "porch" thumbnail to /img/porch.jpg
```

Back in 2.8.3, `get_http_webhooks(url.format(cam_name=uri, img=str(img)), msg, img)` handled the cam_name format. In 2.9.x+ there doesn't appear to be a url.format(cam_name=...) call anywhere so this is going unhandled. 

adding `url = url.format(cam_name=camera, img=str(img))` to webhooks.send_webhook seems to fix it, but that might not be the optimal solution.

### Affected Bridge Version

2.9.x to main

### Bridge type

Docker Run/Compose

### Affected Camera(s)

all

### Affected Camera Firmware

all

### docker-compose or config (if applicable)

```yaml
wyze-bridge:
      image: mrlt8/wyze-bridge
      restart: unless-stopped
      network_mode: "host"
      environment:
        ENABLE_AUDIO: true
        WB_AUTH: false
        WYZE_PASSWORD: 
        API_ID: 
        MOTION_WEBHOOKS: 'http://localhost:8555/motion?{cam_name}'
        MOTION_API: true
        WYZE_EMAIL: 
        API_KEY:
```
