### ISSUE TITLE
BUG: WB_Auth disabled, but still prompted for RTSP feed ID/PW?

### ISSUE THREAD

**Issue by walk0080** [mrlt8/docker-wyze-bridge#1394]
### Describe the bug

Was unable to get Frigate (in Docker) to connect to a Wyze V4 camera due to authentication errors. Tried VLC to check if I can even access the RTSP feed and the wb/API key would not be accepted. Tried WB_AUTH=False, and I am still being prompted for an ID and Password?

After restarting Wyze-Bridge, I can see in the WebUI the following: "WebUI auth is disabled. docker-wyze-bridge v2.10.3"
Yet I am still being prompted for an ID and password when attempting to access the RTSP feed.

Also tried deleting and re-creating the container with the same problem. Any help appreciated.

### Affected Bridge Version

2.10.3

### Bridge type

Docker Run/Compose

### Affected Camera(s)

Wyze Cam v4

### Affected Camera Firmware

4.52.9.1134

### docker-compose or config (if applicable)

```yaml
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935          # RTMP
            - 8556:8554          # RTSP
            - 8888:8888          # HLS
            - 8889:8889          # WebRTC
            - 8189:8189/udp      # WebRTC/ICE
            - 5002:5000          # WEB-UI (External:Internal Port)
        environment:
         - WYZE_EMAIL=XXXX
         - WYZE_PASSWORD=XXXX
         - API_ID=XXXX
         - API_KEY=XXXX
         - WB_IP=192.168.1.2
         - WB_AUTH=False
```
