### ISSUE TITLE
BUG: Error Reading from Pipe: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by jsholcomb** [mrlt8/docker-wyze-bridge#1396]
### Describe the bug

I am noticing instances where the Wyze Bridge is crashing and the camera will not recover.  The log is filled with the following items: 

wyze-bridge  | [WyzeBridge] Error reading from pipe: filedescriptor out of range in select()

This repeats over and over until the container is restarted.  

It appears this may be tied to a V3 camera.  That is a guess. 

### Affected Bridge Version

v2.10.3

### Bridge type

Docker Run/Compose

### Affected Camera(s)

V3, V4

### Affected Camera Firmware

4.61.0.3

### docker-compose or config (if applicable)

```yaml
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            # [OPTIONAL] Credentials can be set in the WebUI
            # API Key and ID can be obtained from the wyze dev portal: 
            # https://developer-api-console.wyze.com/#/apikey/view
            - WYZE_EMAIL=****
            - WYZE_PASSWORD= ******
            - API_ID= *****
            - API_KEY= *****
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            # - WB_IP=192.168.x.x
            # WebUI and Stream authentication:
            - WB_AUTH=True # Set to false to disable web and stream auth.
            - WB_USERNAME=XXXXXX
            - WB_PASSWORD=XXXXXXX 
            - FILTER_NAMES=Camera1, Camera2 
            - FILTER_BLOCK=true
            - FRONT_DOOR_CAMERA=HD500
```
