### ISSUE TITLE
BUG: Bridge not connecting to Doorbell v1 cam

### ISSUE THREAD

**Issue by mholl1983** [mrlt8/docker-wyze-bridge#1401]
### Describe the bug

As of today, I noticed Wyze Bridge doesn't seem to want to connect to any streams from our Doorbell v1 cam. Let me know if I can provide any further details that would help.

### Affected Bridge Version

v2.10.3

### Bridge type

Docker Run/Compose

### Affected Camera(s)

Wyze Doorbell v1

### Affected Camera Firmware

4.25.1.333

### docker-compose or config (if applicable)

```yaml
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            # [OPTIONAL] Credentials can be set in the WebUI
            # API Key and ID can be obtained from the wyze dev portal: 
            # https://developer-api-console.wyze.com/#/apikey/view
            - WYZE_EMAIL=
            - WYZE_PASSWORD= 
            - API_ID=
            - API_KEY= 
            - ROTATE_CAM_BACK_DOOR=True
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            # - WB_IP=192.168.1.122
            # WebUI and Stream authentication:
            - WB_AUTH=False # Set to false to disable web and stream auth.
            # WB_USERNAME=
            # WB_PASSWORD=
```
