### ISSUE TITLE
WebRTC not working when running the image on Lima in macOS

### ISSUE THREAD

**Issue by spamwax** [mrlt8/docker-wyze-bridge#1423]
Everything else (rtsp, hls, ...) is working and accessible from different clients.
It is just that the one I really need (WebRTC) is not working :D

Here is my config:

```yaml
version: "3"
services:
  wyze-bridge:
    container_name: wyze-bridge
    restart: unless-stopped
    image: mrlt8/wyze-bridge:latest
    network_mode: host
    ports:
      - 1935:1935 # RTMP
      - 8554:8554 # RTSP
      - 8888:8888 # HLS
      - 8889:8889 #WebRTC
      - 8189:8189/udp # WebRTC/ICE
      - 5001:5000 # WEB-UI. Note on macOS, port 5000 is used by ControlCenter so we have to change it the first one from 5000 to 5001
    environment:
      - NET_MODE=LAN
      - ON_DEMAND=False
      - WYZE_EMAIL=${WYZE_EMAIL}
      - WYZE_PASSWORD=${WYZE_PASSWORD}
      - API_ID=${API_ID}
      - API_KEY=${API_KEY}
      - WB_IP=0.0.0.0
      - WB_BIND_ADDR=0.0.0.0
      # WebUI and Stream authentication:
      - WB_AUTH=True # Set to false to disable web and stream auth.
      - STREAM_AUTH=:@${CAMERA_NAME}|::${KLIPPER_IP}@${CAMERA_NAME}
      - WB_USERNAME=${WB_USERNAME}
      - WB_PASSWORD=${WB_PASSWORD}
```

Even in the WebUI, when I select the WebRTC from the drop down menu, it just shows a thumbnail and clicking on the play icon does nothing
