### ISSUE TITLE
BUG: Floodlight V2 bitrate too low (bad compression)

### ISSUE THREAD

**Issue by shawnsi** [mrlt8/docker-wyze-bridge#1427]
### Describe the bug

I've noticed that among 3 types of cameras I use only my floodlight v2 models exhibit lower bitrate on all streams. This happens on 2 models I use but can't be reproduced on a doorbell v2 or either cam v4 I also use regularly.

Currently, I have this configuration for cam quality:
```
            - QUALITY_BACK_PATIO=HD1500 # floodlight v2
            - QUALITY_SOUTH_GARDEN=HD1500 # floodlight v2
            - QUALITY_FRONT_PORCH=HD500
            - QUALITY_UNDER_DECK=HD500
            - QUALITY_FRONT_DOORBELL=HD500
```

The actual bitrate of the floodlights appears to be 3-4x lower than the other cams. This is the case in storage measured for recordings and also when viewing bitrate statistics of the streams in vlc.

Is the fact that this logging still says "SD" in quality prefix significant? These lines are after the cam was restarted to force reconnection.
```
2025-02-14 16:17:36.569
[back-patio] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
2025-02-14 16:17:36.489
[back-patio] 📡 Getting 1500kb/s SD stream (H264/20fps) via LAN mode (WiFi: 70%) FW: 4.53.3.9759 🔒
```

Anything else I can do to debug bitrate/compression issues on the floodlight v2? Can I control key frame interval in anyway? That might mitigate the compression artifacts I'm fighting as well.

### Affected Bridge Version

2.10.3

### Bridge type

Docker Run/Compose

### Affected Camera(s)

Wyze Cam Floodlight V2 [2k]

### Affected Camera Firmware

4.53.3.9759

### docker-compose or config (if applicable)

```yaml
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:2.10.3
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            # [OPTIONAL] Credentials can be set in the WebUI
            # API Key and ID can be obtained from the wyze dev portal: 
            # https://developer-api-console.wyze.com/#/apikey/view
            - WYZE_EMAIL=REDACTED
            - WYZE_PASSWORD=REDACTED
            - API_ID=REDACTED
            - API_KEY=REDACTED
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            # - WB_IP=192.168.1.122
            # WebUI and Stream authentication:
            - WB_AUTH=false # Set to false to disable web and stream auth.
            - WB_USERNAME=user
            - WB_PASSWORD=pass
            #- WB_IP=InternalWyzeIP
            #- WB_IP=ExtarnalHomeIP
            #- MTX_WEBRTCLOCALTCPADDRESS=:8189
            #- NET_MODE=LAN
            #- KEEP_BAD_FRAMES=True
            #- FRESH_DATA=True
            - TZ=America/Chicago
            - RECORD_ALL=True
            - RECORD_PATH=/recordings/{cam_name}
            - RECORD_FILE_NAME={cam_name}%Y%m_%d_%H_%M_%S
            - RECORD_LENGTH=1800s
            - RECORD_KEEP=168h
            #- SUBSTREAM_FRONT_PORCH=True
            #- SUBSTREAM_FRONT_DOORBELL=True
            #- SUBSTREAM_SOUTH_GARDEN=True
            #- SUBSTREAM_BACK_PATIO=True
            #- SUBSTREAM_UNDER_DECK=True
            #Quality settings
            #https://github.com/mrlt8/docker-wyze-bridge/wiki/Camera-Bitrate-and-Resolution
            # - ENABLE_AUDIO=false
            # - ON_DEMAND=false
            # - FORCE_FPS=10
            # - FIX_FPS=true
            - QUALITY_BACK_PATIO=HD1500
            - QUALITY_SOUTH_GARDEN=HD1500
            - QUALITY_FRONT_PORCH=HD500
            - QUALITY_UNDER_DECK=HD500
            - QUALITY_FRONT_DOORBELL=HD500
            - MTX_LOGLEVEL=info
            - MTX_PATHS_FRONT-DOORBELL-HALF=
            - MTX_PATHS_FRONT-DOORBELL_RUNONREADYRESTART=yes
            - MTX_PATHS_FRONT-DOORBELL_RUNONREADY=ffmpeg -rtsp_transport tcp -i rtsp://localhost:$$RTSP_PORT/$$MTX_PATH -c:v libx264 -vf "scale=iw/2:ih/2" -preset ultrafast -tune zerolatency -r 5 -g 5 -crf 22 -f rtsp rtsp://0.0.0.0:$$RTSP_PORT/$$MTX_PATH-half
            - MTX_PATHS_UNDER-DECK-HALF=
            - MTX_PATHS_UNDER-DECK_RUNONREADYRESTART=yes
            - MTX_PATHS_UNDER-DECK_RUNONREADY=ffmpeg -rtsp_transport tcp -i rtsp://localhost:$$RTSP_PORT/$$MTX_PATH -c:v libx264 -vf "scale=iw/2:ih/2" -preset ultrafast -tune zerolatency -r 5 -g 5 -crf 22 -f rtsp rtsp://0.0.0.0:$$RTSP_PORT/$$MTX_PATH-half
            - MTX_PATHS_SOUTH-GARDEN-HALF=
            - MTX_PATHS_SOUTH-GARDEN_RUNONREADYRESTART=yes
            - MTX_PATHS_SOUTH-GARDEN_RUNONREADY=ffmpeg -rtsp_transport tcp -i rtsp://localhost:$$RTSP_PORT/$$MTX_PATH -c:v libx264 -vf "scale=iw/2:ih/2" -preset ultrafast -tune zerolatency -r 5 -g 5 -crf 22 -f rtsp rtsp://0.0.0.0:$$RTSP_PORT/$$MTX_PATH-half
            - MTX_PATHS_BACK-PATIO-HALF=
            - MTX_PATHS_BACK-PATIO_RUNONREADYRESTART=yes
            - MTX_PATHS_BACK-PATIO_RUNONREADY=ffmpeg -rtsp_transport tcp -i rtsp://localhost:$$RTSP_PORT/$$MTX_PATH -c:v libx264 -vf "scale=iw/2:ih/2" -preset ultrafast -tune zerolatency -r 5 -g 5 -crf 22 -f rtsp rtsp://0.0.0.0:$$RTSP_PORT/$$MTX_PATH-half
            - MTX_PATHS_FRONT-PORCH-HALF=
            - MTX_PATHS_FRONT-PORCH_RUNONREADYRESTART=yes
            - MTX_PATHS_FRONT-PORCH_RUNONREADY=ffmpeg -rtsp_transport tcp -i rtsp://localhost:$$RTSP_PORT/$$MTX_PATH -c:v libx264 -vf "scale=iw/2:ih/2" -preset ultrafast -tune zerolatency -r 5 -g 5 -crf 22 -f rtsp rtsp://0.0.0.0:$$RTSP_PORT/$$MTX_PATH-half
        volumes:
            - /storage/security/recordings:/recordings
        networks:
            - proxynet

networks:
  proxynet:
    name: proxynet
    external: true
```
