### ISSUE TITLE
I have 12 cameras 3 Pro all of them stopped recording on the server yesterday. What’s happening?

### ISSUE THREAD

**Issue by ehabnt** [mrlt8/docker-wyze-bridge#1433]
### Describe the bug

I have 12 cameras 3 Pro all of them stopped recording on the server yesterday. What’s happening?

### Affected Bridge Version

image ID: 518e804f6636

### Bridge type

Docker Run/Compose

### Affected Camera(s)

12 cameras v3 pro 

### Affected Camera Firmware

Lastest version 4.58.13.1321

### docker-compose or config (if applicable)

```yaml
---
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 # WebRTC
            - 8189:8189/udp # WebRTC/ICE            
            - 5000:5000 # WEB-UI
            - 9997:9997 # Expose port for API
        environment:
            - WYZE_EMAIL=xxxxxxxxxxxxxxxxxxxx
            - WYZE_PASSWORD=xxxxxxxxxxxxxxx
            - API_ID=xxxxxxxxxxxxxxxxxxxxxxx
            - API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            - WB_IP=xxxxxxxxxxxxxxxxxx
            - WB_AUTH=True
            - WB_USERNAME=xxxxxxxxxxxxxxxx
            - WB_PASSWORD=xxxxxxxxxxxxxxx
            - NET_MODE=LAN
            - ON_DEMAND=False
            - TZ=xxxxx/xxxxx
            - RECORD_ALL=True
            - RECORD_LENGTH=3600s
            - RECORD_PATH=/record/{cam_name}/{cam_name}_%Y-%m-%d_%H-%M-%S
            - ENABLE_AUDIO=True
            - RECORD_KEEP=0s
            - IGNORE_OFFLINE=true
            - FPS_FIX=true
            - ENABLE_BOA=true
        volumes:
            - /xxxx/xxxx/xxxx/xxxx:/xxxx/
```
