### ISSUE TITLE
BUG: Cameras screenshot loads but dont play

### ISSUE THREAD

**Issue by Boundzero** [mrlt8/docker-wyze-bridge#1435]
### Describe the bug

Im not sure what happened but my Wyze bridge used to load my video automatically and play. Now they just spin the loading symbol and never play. If i look at the one of the cameras information I see it says connected = false. Whats going wrong? Any ideas? 

### Affected Bridge Version

Latesat

### Bridge type

Docker Run/Compose

### docker-compose or config (if applicable)

```yaml
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            # [OPTIONAL] Credentials can be set in the WebUI
            # API Key and ID can be obtained from the wyze dev portal: 
            # https://developer-api-console.wyze.com/#/apikey/view
            - WYZE_EMAIL=REMOVED
            - WYZE_PASSWORD=REMOVED 
            - API_ID=REMOVED
            - API_KEY= REMOVED
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            # - WB_IP=192.168.1.122
            # WebUI and Stream authentication:
            - WB_AUTH=True # Set to false to disable web and stream auth.
            # WB_USERNAME=
            # WB_PASSWORD=
```

**Comment by Boundzero** [comment]
Resolved it by changing from bridge to host

**Comment by Raul-7-7** [comment]
@Boundzero I have the same issue, where did you make this change?

**Comment by StoneLegion** [comment]
Edit: Just add `network_mode: host`

Example:
```
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        network_mode: host
        image: mrlt8/wyze-bridge:dev
```
