### ISSUE TITLE
BUG: Three supported cameras and Bridge only connects to Doorbell Cam v1, not the other two v3 Cams.

### ISSUE THREAD

**Issue by mholl1983** [mrlt8/docker-wyze-bridge#1452]
### Describe the bug

Hi, hope I'm explaining this properly, but for a few weeks now, Bridge has only worked with my v1 Doorbell Cam, not my other two v3 Cams. Here's a screenshot side by side (v3 on the left, v1 Doorbell on the right):

![Image](https://github.com/user-attachments/assets/4b7be7f3-c7ce-4280-b10d-7cb27b19df5a)

I see recent posts about workarounds, but none of those work for me (host network mode, removing ports etc). Any suggestions? 

### Affected Bridge Version

 v2.10.3

### Bridge type

Docker Run/Compose

### Affected Camera(s)

Cam v3

### Affected Camera Firmware

4.36.13.0416 (but it's been on that firmware for quite awhile, so don't know if that's a factor.

### docker-compose or config (if applicable)

```yaml
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            # [OPTIONAL] Credentials can be set in the WebUI
            # API Key and ID can be obtained from the wyze dev portal: 
            # https://developer-api-console.wyze.com/#/apikey/view
            - WYZE_EMAIL=
            - WYZE_PASSWORD=
            - API_ID=
            - API_KEY=
            - ROTATE_CAM_BACK_DOOR=True
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            # - WB_IP=
            # WebUI and Stream authentication:
            - WB_AUTH=False # Set to false to disable web and stream auth.
            # WB_USERNAME=
            # WB_PASSWORD=
```
