### ISSUE TITLE
BUG: issues stopping container

### ISSUE THREAD

**Issue by tabooki** [mrlt8/docker-wyze-bridge#1468]
### Describe the bug

Having problems every time I try to stop or restart the container. I get a permission denied error. 

### Affected Bridge Version

Latest

### Bridge type

Docker Run/Compose

### Affected Camera(s)

Wyze

### docker-compose or config (if applicable)

```yaml
# to restart use docker-compose up -d --force-recreate
# docker logs wyze-bridge
# update with
# docker pull mrlt8/wyze-bridge


version: '2.9'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
      #  image: mrlt8/wyze-bridge:edge
        image: mrlt8/wyze-bridge:latest
       # image: mrlt8/wyze-bridge:dev
        
        ports:
            - 10.0.0.1:1935:1935 # RTMP
            - 10.0.0.1:8554:8554 # RTSP
            - 10.0.0.1:8888:8888 # HLS
            - 10.0.0.1:8889:8889 #WebRTC
            - 10.0.0.1:8189:8189/udp # WebRTC/ICE
            - 10.0.0.1:5000:5000 # WEB-UI
       # mem_limit: 2048m
        cpus: "1.0"
          
        environment:

           # - WB_USERNAME=phlegm
           # - WB_PASSWORD=xxx
            - WB_AUTH=false

#test for issues
      #      - network_mode=Host


#ENABLE_AUDIO=false
            # [OPTIONAL] Credentials can be set in the WebUI
            # API Key and ID can be obtained from the wyze dev portal: 
            # https://developer-api-console.wyze.com/#/apikey/view
            - WYZE_EMAIL=xxxx@gmail.com
            - WYZE_PASSWORD=xxxx
            - API_ID=xxxx
            - API_KEY=xxxx
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            # - WB_IP=192.168.1.122
            #
            # get rid of keyframe error
            #- IGNORE_RES=1
            #Set Quality 
            #- QUALITY=HD300
            #- QUALITY=HD120
            #- QUALITY=HD6500        # Setting high quality for the stream
            #- FRAMESIZE=1920x1080

            #- FORCE_FPS_CATCAM=15
            
            # Testing Persistent Connection option for disconnects
            # https://github.com/mrlt8/docker-wyze-bridge/wiki/Advanced-Option#persistent-connection
            - ON_DEMAND=False
            
            # Filter out the cams not needed. only allow listed
            - FILTER_NAMES=Cat Cam
            
            #Enable streaming to restream or youtube
            #
            - LIVESTREAM_CAT_CAM=rtmp://live.restream.io/xxxx
```
