### ISSUE TITLE
BUG: Please include "network_mode: host" in sample configs

### ISSUE THREAD

**Issue by richardhughes260** [mrlt8/docker-wyze-bridge#1481]
### Describe the bug

I really appreciate this work. 

I had the micro sd card die with my old config, that also was not backed up.

I burned a number of hours troubleshooting my new installation. This could have been avoided  if this was included in the config:

#network_mode: host # Use this if running not in Home Assistant

Deep appreciation for this code! I love the ability to have one view for 3 different manufacturers of cameras combined into one UI & this is a key part of that.

Thank you!

### Affected Bridge Version

2.10.3

### Bridge type

Docker Run/Compose

### Affected Camera(s)

N/A

### Affected Camera Firmware

N/A

### docker-compose or config (if applicable)

```yaml
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        network_mode: host
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            # [OPTIONAL] Credentials can be set in the WebUI
            # API Key and ID can be obtained from the wyze dev portal: 
            # https://developer-api-console.wyze.com/#/apikey/view
```
