### ISSUE TITLE
High bandwidth/data usage

### ISSUE THREAD

**Issue by mr-bobdobalina** [mrlt8/docker-wyze-bridge#23]
When I have the wyze-bridge up, I see my router has traffic going out Port 10001 UDP from my 3 Wyze Cams. I believe it is all coming right back to the machine that I have the wyze-bridge running. As far as I can tell these are related to Wyze's servers.  So is this "bridge" simply acting like a Wyze app that can stream all the cameras simultaneously? I was hoping it was more of a local connection only bypassing Wyze servers completely (except for the initial API hit to get camera listing and IPs). 

If that is not the case, then there should be a disclaimer stating so in case people have bandwidth caps from their ISP. My 3 cameras alone are probably chewing up close to 3 GB an hour. That's 504 GB a week, a typical cable ISP in the US has a 1.2TB data cap.  Using this bridge would burn through that in a little over 2 weeks!

**Comment by mrlt8** [comment]
looking into this.

**Comment by mr-bobdobalina** [comment]
Pulled changes, getting the same "Relay mode". For now I downgraded my streams to SD240 but it's still almost 1GB an hour.

**Comment by mrlt8** [comment]
Hey @mr-bobdobalina, I pushed a new update that should get you a local stream _if on linux_. 
You'll need to update your docker-compose.yml and uncomment the `network_mode: host` line and delete all the `ports` lines. Something like this:
```yaml
    wyze-bridge:
        restart: always
        network_mode: host
        build: 
            context: ./app
            # dockerfile: Dockerfile.arm
        environment:
            ...
```

Unfortunately, this only seems to work on linux based systems at the moment.

Open to ideas if anyone knows how to configure docker to work with UDP multicast without host networking on other OS's!
