### ISSUE TITLE
One cam keeps disconnecting, when two cameras configured. 

### ISSUE THREAD

**Issue by pdxbrit** [mrlt8/docker-wyze-bridge#240]
Great utility! But I'm having an issue when I have two cameras configured and connected at the same time, one of the cameras cannot get a stable connection. It's always the same camera, and if I deconfigure/block the second camera the one that cannot connect will work fine. I didn't see anything obvious in the logs, but I am pretty new to this software. 

I'm using an ancient version (3.0.3) of Sighthound for macOS on my 10.13.6 iMac as the client. Before switching over to Wyze v3 cams, and wyze-bridge it was supporting two HD foscam streams. 

In the attached debug log there are two cameras, `front-porch-cam` and `garagecam`. `garagecam` fails to stay connected whenever `front-porch-cam` is configured, `front-porch-cam` always works. `garagecam` works when it's the only camera configured. 

I noticed today that `garagecam` is upgraded to the `4.36.6.17` firmware, but that `front-porch-cam` is running `4.36.3.19`. Do both cameras need to be on the same firmware version?  

Both cameras are connected to the same WiFi network, and the Wyze app is still streaming when it fails to connect. 

```
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest # Use a prebuilt image
        # build:  # Uncomment to build from source
        #     context: ./app # Uncomment to build from source
        #     # dockerfile: Dockerfile.arm # Uncomment to build for arm
        ports:
            - 1935:1935
            - 8554:8554
            - 8889:8889
        environment:
            - FILTER_NAMES=Lake Cam
            - FILTER_BLOCK=true
            - NET_MODE=LAN
            - WYZE_EMAIL=email
            - WYZE_PASSWORD=password
            - DOCKER_HOST=192.168.1.114
            - TZ=America/Los_Angeles
            - DEBUG_LEVEL=debug
            - RTSP_LOGLEVEL=debug
```
[Wyze-Bridge-Log.txt](https://github.com/mrlt8/docker-wyze-bridge/files/7577165/Wyze-Bridge-Log.txt)

**Comment by pdxbrit** [comment]
I've realized that for some reason I'm still running `1.0.2` , how do I force docker to pickup `1.0.3` my `docker-compose.yml` specifies `image: mrlt8/wyze-bridge:latest` which I thought would pick up the latest?

**Comment by frakman1** [comment]
Have you tried doing this to force a pull?

```bash
docker-compose stop
docker-compose rm -f
docker-compose pull   
docker-compose up -d
```

Also, according to [this](https://stackoverflow.com/a/66136860/3439096), `docker-compose` supports a `pull_policy` directive that allows you to specify when it pulls images.
``` 
pull_policy: always
```

**Comment by KaneHart** [comment]
> Have you tried doing this to force a pull?
> 
> ```shell
> docker-compose stop
> docker-compose rm -f
> docker-compose pull   
> docker-compose up -d
> ```
> 
> Also, according to [this](https://stackoverflow.com/a/66136860/3439096), `docker-compose` supports a `pull_policy` directive that allows you to specify when it pulls images.
> 
> ```
> pull_policy: always
> ```

Thank you this had fixed my issue the first part. I guess one my new camera's was the new firmware and was being disabled I saw a broken heart and D something. Anyways doing this got me the correct new version. I guess I was failing at pulling updates.

**Comment by frakman1** [comment]
Mine just stopped working recently and updating to the latest image fixed it. 
I took my own advice and added the `pull_policy` instruction to the `docker-compose.yml` file.
I am using Portainer to deploy the container.

`docker-compose:`
```yaml
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest # Use a prebuilt image
        pull_policy: always
        # build:  # Uncomment to build from source
        #     context: ./app # Uncomment to build from source
        #     # dockerfile: Dockerfile.arm # Uncomment to build for arm
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
        environment:
            - WYZE_EMAIL=${WYZE_EMAIL} # Replace with wyze email 
            - WYZE_PASSWORD=${WYZE_PASSWORD} # Replace with wyze password
            - NET_MODE=LAN
            - FILTER_NAMES=Living Room Cam
            - TZ=America/New_York
```

Output:
![image](https://user-images.githubusercontent.com/5826484/147011874-96d86e7d-166f-465f-ad5c-51133266e07b.png)


For completeness, this is the setting I used in Home Assisstant's `configuration.yml` file to access this feed:

`configuration.yml`:
```yaml
camera:
  - platform: ffmpeg
    name: "Wyze-LivingRoom"
    input: "rtsp://server-ip:8554/living-room-cam"
```
