### ISSUE TITLE
Noob assistance; How do I add the HLS stream to HA?

### ISSUE THREAD

**Issue by jcandresen** [mrlt8/docker-wyze-bridge#267]
I found my configuration.yaml file and tried adding 

camera:
  - platform: generic
    still_image_url: http://192.168.0.20:8888/office-cam/

but it just shows as idle in homeassistant?
![image](https://user-images.githubusercontent.com/23084292/145649781-4f700dcd-cd0f-4ed6-be51-93dbda2c887a.png)

Apologies if this is too noob, im pretty new to HA.

**Comment by mrlt8** [comment]
You'll probably get better performance if you use the RTSP stream with something like:
```
camera:
  - platform: generic
    still_image_url: http://127.0.0.1:8123/local/office-cam.jpg
    stream_source: rtsp://127.0.0.1:8554/office-cam
```

**Comment by frakman1** [comment]
Agree with @mrlt8 about using RTSP. That's how I set mine up too. Similar but slightly different syntax for me is:
```yaml
camera:
  - platform: ffmpeg
    name: "Wyze-LivingRoom"
    input: "rtsp://server-ip:8554/living-room-cam"
```
Replace `server-ip` with your actual server IP address.
