### ISSUE TITLE
url or service for snapshots

### ISSUE THREAD

**Issue by stenwt** [mrlt8/docker-wyze-bridge#269]
I'm trying to figure out where to find the snapshots this application creates when I set "SNAPSHOT=RTSP". I'm running the application in k3s with this deployment manifest: 

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wyze-bridge
  name: wyze-bridge
  namespace: wyze-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wyze-bridge
  strategy: {}
  template:
    metadata:
      labels:
        app: wyze-bridge
    spec:
      containers:
      - image: mrlt8/wyze-bridge:latest
        name: wyze-bridge
        resources: {}
        env:
        - name: WYZE_EMAIL
          valueFrom:
            secretKeyRef:
              name: wyze-secret
              key: WYZE_EMAIL
        - name: WYZE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wyze-secret
              key: WYZE_PASSWORD
        - name: NET_MODE
          value: P2P
        - name: SNAPSHOT
          value: RTSP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wyze-bridge
  name: wyze-bridge
  namespace: wyze-bridge
spec:
  ports:
  - name: "rtsp"
    port: 8554
    protocol: TCP
    targetPort: 8554
  - name: "http"
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: wyze-bridge
  sessionAffinity: None
  type: ClusterIP
```

With this configuration, I can watch the RTSP streams at e.g. rtsp://wyze-bridge.wyze-bridge.svc.cluster.local:8554/garage , but if I curl like this, I get redirected to an empty resource: 

```
bash-5.1# curl -vl http://wyze-bridge.wyze-bridge.svc.cluster.local:8888/img/garage.jpg
*   Trying 10.43.242.231:8888...
* Connected to wyze-bridge.wyze-bridge.svc.cluster.local (10.43.242.231) port 8888 (#0)
> GET /img/garage.jpg HTTP/1.1
> Host: wyze-bridge.wyze-bridge.svc.cluster.local:8888
> User-Agent: curl/7.78.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: *
< Location: /img/garage.jpg/
< Server: rtsp-simple-server
< Date: Sat, 18 Dec 2021 20:32:10 GMT
< Content-Length: 0
<
* Connection #0 to host wyze-bridge.wyze-bridge.svc.cluster.local left intact
```
