### ISSUE TITLE
Monitor docker bridge?

### ISSUE THREAD

**Issue by SomebodySysop** [mrlt8/docker-wyze-bridge#277]
Is there a way to monitor docker-wyze-bridge?  Right now, the only way I know if it has gone down is if I don't see any cameras up on the monitor.  It would be nice to be able to monitor when it goes down in order to bring it back up if necessary.

I have Uptime Kuma installed which will allow me to monitor individual tcp ports, and I thought about monitoring port 8554 on the docker-wyze-bridge machine, but will that port still have activity even if all the cameras are down?  What about port 1935 on the machine?  Will all activity on that port cease if NO camera is alive on the bridge?

If anyone has a method for automated monitoring of their bridge, I'm interested to learn how you do it.

**Comment by mrlt8** [comment]
Take a look at #204.
You may be able to do something with the [rtsp-simple-server api](https://aler9.github.io/rtsp-simple-server/):

```yaml
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
            - 9997:9997 # Expose port for API
        environment:
            - RTSP_APIADDRESS=0.0.0.0:9997 # Config port for API
            - RTSP_API=yes # Enable API
            - WYZE_EMAIL=
            - WYZE_PASSWORD=
```
