### ISSUE TITLE
RTSP Video Lag & Stuttering

### ISSUE THREAD

**Issue by Rustymage** [mrlt8/docker-wyze-bridge#278]
Hi,

I have this bridge installed on Home Assistant (RPi 4 running off SSD & ethernet). I connect a Synology DS920+ to it using the surveilance package. The camera is a v3 with 128Gb SD card installed (and recognised), it is also continuously recording.

Recently I've started to review recorded footage and found that there are parts of the recording where the video stutters and jumps around. For example, a person walking their dog past the property jumps a few seconds into the future, then pings about between the original time and the new one before the footage settles and continues. You can see the timestamp from Wyze jumping too. 

Using the Wyze app, the playback is smooth and as expected.

I am on the latest camera, HA, bridge & Wyze FW.

Help please..?

**Comment by Rustymage** [comment]
I also note that the FPS is all over the place and I believe this is causing the timelines to become misaligned to the Synology capture time.

Having just installed the Wyze RTSP FW, the issues appear to have gone away - although with an impending FW update, I'm not sure if this will last?

**Comment by xconverge** [comment]
This matches what I was seeing and starting to try and discuss in https://github.com/mrlt8/docker-wyze-bridge/issues/221

**Comment by Rustymage** [comment]
> This matches what I was seeing and starting to try and discuss in https://github.com/mrlt8/docker-wyze-bridge/issues/221

I wasn't 100% so I figured I'd start a new issue.

I found moving to the RTSP FW fixed my issues, however I prefer the implementation offered here due to the fact I can stay on the latest FW (present issue noted).

**Comment by mrlt8** [comment]
Could you see if v1.2.0 improves/resolves this issue?

**Comment by Rustymage** [comment]
v1.2.0 doesn't improve this. v2.6.0 doesn't either - sorry for the delay in feeding this back.

Here's a clip of the issue I'm having.

https://github.com/mrlt8/docker-wyze-bridge/assets/19926955/1b9b5401-074d-4ca7-a038-10f4d914a6c2

docker-compose.yml
```
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:dev-qsv
        ports:
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        env_file:
            - .env
```

.env
```
API_ID= XXXX-XXXX-XXXX
MQTT_HOST=192.168.1.141:1883
MQTT_AUTH=mqtt:XXXX
MQTT_TOPIC=wyzebridge
QUALITY=HD120
WYZE_EMAIL=XXXX
WYZE_PASSWORD= XXXX
H264_ENC=h264_qsv
NET_MODE=P2P
```

**Comment by Rustymage** [comment]
Please note that I now run this off a VM, not an RPi.

**Comment by mrlt8** [comment]
hmm, seems like it could potentially be a connection issue?

You'll need to set `- FORCE_ENCODE=true` if you want to re-encode the video.

Can you also post the build date of the container from the logs?

**Comment by Rustymage** [comment]
This is the image I'm using: [`mrlt8/wyze-bridge:dev-qsv@sha256:517c7ff2de78c81e0b02eab91341d225e8fd754b266588cec17495e918b83da0](https://192.168.1.110:9443/#!/15/docker/images/sha256%3A517c7ff2de78c81e0b02eab91341d225e8fd754b266588cec17495e918b83da0)`

The image was created on my system here - `2024-01-06T15:45:24.739Z`

The camera is about 2m away from a Reolink on the same Wifi network with no issues. The connection to my network is about 5m away utilising a Unifi AP (U6 lite). Signal strength is -66dBm. The Reolink is -60dBm.

**Comment by Rustymage** [comment]
`FORCE_ENCODE=true` didn't work as FFMPEG stopped working. So I've moved back to the following:

```
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        env_file:
            - .env
```

I've watched the stream for a few minutes and it's not as bad, despite the same version (v2.6.0).
