### ISSUE TITLE
Pi Zero W

### ISSUE THREAD

**Issue by socalcal** [mrlt8/docker-wyze-bridge#294]
Does this work on a Pi Zero W? I'm running a Homebridge image on a Pi Zero W and get this when trying to start the docker: 

```
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm/v6) and no specific platform was requested
docker: Error response from daemon: driver failed programming external connectivity on endpoint priceless_heisenberg (b26b8e69144bd3d7fbb983d24e58deaddbcc27a8a2f1597cfa5f900d207298af): Error starting userland proxy: listen tcp6 [::]:8888: bind: address already in use.
```

So first issue is leading me to believe that v6 is not supported? Second issue is port 8888 is already being used by something else. I'm a follow-directions-and-install kind of guy so no idea what can be causing this issue. Not sure if it's the Homebridge image itself or another plug-in that I'm running. Any and all help appreciated. Thanks!

**Comment by mrlt8** [comment]
I don't have an armv6 device to test on, but I added a dockerfile that should be able to build an image using the arm library (not sure if it will run on the v6 though).

You'll need to git clone or download the repo and create a `docker-compose.yml` file with something like this:
```yaml
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        build:
            context: ./app
            dockerfile: Dockerfile.armv6
        ports:
            - 1935:1935
            - 8554:8554
            - 8080:8888 # This will expose 8080 instead of 8888 for the HLS streams
        environment:
            - WYZE_EMAIL=${WYZE_EMAIL} # Replace with wyze email 
            - WYZE_PASSWORD=${WYZE_PASSWORD} # Replace with wyze password
```

you should then be able to run `docker-compose up` to build the container from the source.

You can also replace the `- 8080:8888` line with whatever port you want or remove it if you don't need the HLS stream.
