### ISSUE TITLE
unable to connect to cameras (404)

### ISSUE THREAD

**Issue by TristanBrotherton** [mrlt8/docker-wyze-bridge#397]
I've had trouble configuring this to work correctly. I see the server connecting via http, but every camera gives me a 404. I get this in the logs:

```
wyze-bridge    | Sleeping for 10s...
wyze-bridge    | 2022/05/27 05:13:02 I [0/0] [HLS] [conn 192.168.167.213:50836] GET /garden/
wyze-bridge    | 2022/05/27 05:13:02 I [0/0] [HLS] [remuxer garden] created
wyze-bridge    | 2022/05/27 05:13:02 I [0/0] [HLS] [remuxer garden] ERR: no one is publishing to path 'garden'
wyze-bridge    | 2022/05/27 05:13:02 I [0/0] [HLS] [remuxer garden] destroyed
wyze-bridge    | 2022/05/27 05:13:08 [MainThread] 🌎 Fetching 'cameras' from the Wyze API...
wyze-bridge    | 2022/05/27 05:13:09 [MainThread] 
```

docker-compose.yml: 
```
version: '3.3'
services:
    wyze-bridge:
        container_name: wyze-bridge
        #restart: always
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
        # Uncomment to use a pre-built image:
        # image: mrlt8/wyze-bridge:latest
        # or build from source:
        build:
            context: ./app
            # Uncomment to build for arm
            # dockerfile: Dockerfile.arm 
        environment:
            - WYZE_EMAIL=xxx@xxx.com
            - WYZE_PASSWORD=xxxx
        volumes:
            - ./tokens:/tokens/
```

EDIT:

I updated the docker-compose.yml to the latest example:

```
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
        environment:
            - WYZE_EMAIL=xxx
            - WYZE_PASSWORD=xxx
```
Which now results in what appears to be an authentication failure:

wyze-bridge    | 2022/05/27 05:32:31 [WyzeBridge] 🔍 Could not find local cache for 'user'
wyze-bridge    | 2022/05/27 05:32:31 [WyzeBridge] 🔍 Could not find local cache for 'auth'
wyze-bridge    | 2022/05/27 05:32:31 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge    | 2022/05/27 05:32:31 [WyzeBridge] 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/user/login

I'm running Wyze v3 cams, and the container is running on a dedicated ubuntu 20.04.4 LTS
Could anyone point me in the right direction?
