### ISSUE TITLE
Getting 400 error on app trying to auth, but 200 w/curl

### ISSUE THREAD

**Issue by elreydetoda** [mrlt8/docker-wyze-bridge#413]
So, I looked at the code and I followed the exact same steps that you do for authenticating to the API (but through CLI commands (commands below)), and the app keeps saying it has a 400 error but I was able to properly authenticate with the CLI commands + curl (pic below, sensitive info redacted).

![image](https://user-images.githubusercontent.com/10230166/173002448-5138c45a-991e-4e80-b9b7-5094aa4fb7bd.png)

commands used to generate phone id header + 3md5 password
```
# generate phone id header
python3 -c 'from uuid import uuid4; print(uuid4())'
# generate 3md5 hash
# first time password
python3 -c 'from hashlib import md5; print(md5("<text>".encode("ascii")).hexdigest())'
# second time is contents from last command
python3 -c 'from hashlib import md5; print(md5("<text>".encode("ascii")).hexdigest())'
# third time is contents from last command
python3 -c 'from hashlib import md5; print(md5("<text>".encode("ascii")).hexdigest())'
```

I even changed my password to only be alphanumeric + removed mfa to see if that was the issue, and still no... only other "special" character involved with input is a `.` in parts of the email (i.e. bobby.tables@gmail.com).

```
wyze-bridge    | 2022/06/10 01:59:27 [WyzeBridge][INFO][WyzeBridge] ?? Fetching 'auth' from the Wyze API...
wyze-bridge    | 2022/06/10 01:59:27 [urllib3.connectionpool][DEBUG][WyzeBridge] Starting new HTTPS connection (1): auth-prod.api.wyze.com:443
wyze-bridge    | 2022/06/10 01:59:27 [urllib3.connectionpool][DEBUG][WyzeBridge] https://auth-prod.api.wyze.com:443 "POST /user/login HTTP/1.1" 400 None
wyze-bridge    | 2022/06/10 01:59:27 [WyzeBridge][WARNING][WyzeBridge] ? Invalid credentials?
```

I using the docker-compose sample file + some extra stuff:

```yaml
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        volumes:
            - ./tokens:/tokens
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
        environment:
            - WYZE_EMAIL='<email>' # Replace with wyze email 
            - WYZE_PASSWORD='<pass>' # Replace with wyze password
            - ENABLE_AUDIO=True
            - NET_MODE=LAN
            - SNAPSHOT=RTSP
            - TZ=America/New_York
            - QUALITY_CAM_NAME=HD120
            - DEBUG_LEVEL=debug
```
