### ISSUE TITLE
Still Image

### ISSUE THREAD

**Issue by binarynightowl** [mrlt8/docker-wyze-bridge#42]
I did not see an option in the docs for a still image, is there a workaround for this?

**Comment by mrlt8** [comment]
There is no built-in way, but I could try adding something in the future if there's enough demand.

You could also hack together something in your docker-compose.yml to get a still image via an nginx container like this:
```yaml
version: '3.8'
services:
    wyze-bridge:
        container_name: wyze-bridge
        image: mrlt8/wyze-bridge:latest
        restart: always
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
        volumes: 
            - stills-data:/img
        environment:
            - WYZE_EMAIL=
            - WYZE_PASSWORD=
            # jpg will be available at http://<server-ip>:8080/cam-name.jpg
            # Replace <MY-CAM-NAME-UPPER> and <my-cam-name-lower> for each cam:
            - RTSP_PATHS_<MY-CAM-NAME-UPPER>_RUNONPUBLISH=ffmpeg -hide_banner -nostats -loglevel fatal -i rtsp://0.0.0.0:8554/<my-cam-name-lower> -vframes 1 -y /img/<my-cam-name-lower>.jpg
            - RTSP_PATHS_<MY-CAM-NAME-UPPER>_RUNONPUBLISHRESTART=yes
            # Do the same for each additonal cam:
            - RTSP_PATHS_<MY-CAM-NAME-UPPER>_RUNONPUBLISH=ffmpeg -hide_banner -nostats -loglevel fatal -i rtsp://0.0.0.0:8554/<my-cam-name-lower> -vframes 1 -y /img/<my-cam-name-lower>.jpg
            - RTSP_PATHS_<MY-CAM-NAME-UPPER>_RUNONPUBLISHRESTART=yes
    web:
        container_name: nginx
        image: nginx:mainline-alpine
        restart: always
        ports:
            - 8080:80
        volumes:
            - stills-data:/usr/share/nginx/html
volumes:
    stills-data:
        driver_opts:
            type: tmpfs
            o: size=8m
            device: tmpfs          
```

Not sure if the tmpfs actually works, but it's worth a try to save on writes to your local drive.
