### ISSUE TITLE
Not working with Traefik

### ISSUE THREAD

**Issue by alex-oswald** [mrlt8/docker-wyze-bridge#523]
I'm trying to get the wyze bridge to work with the Traefik reverse proxy. I'm using Traefik for many other services with no issues (pihole, octopi, custom .NET apps, portainer, grafana, home assistant). For whatever reason, I can't access the web ui through the proxy. I can access the web UI just fine through the IP address and port. As an example, I setup Portainer in a similar way. I can access Portainer via the proxy, and via the IP and port if I expose the port in the docker compose file. When I do this same thing with wyze, I cannot access the web UI. I'm hoping maybe I am missing some sort of configuration

Can anyone see a config issue with my docker-compose file?
Has anyone got the wyze bridge UI exposed through Traefik?

Here is my compose file: https://github.com/alex-oswald/HomeInfra/blob/main/cluster/wyze-bridge/docker-compose.yml

**Comment by maxfield-allison** [comment]
Only the web config and HLS streams will work with traefik http services because traefik is only configured as an http proxy. The other issue is that you aren't handling the suffix in any way. you'd have to go to wyze.pi.lan/your-cam-name

idk if you can or how you'd go about using rtmp or rtsp through traefik but i'd imagine you may be able to do some udp or tcp router to make it happen. haven't bothered in my setup. It may just be easier to use something like the recently resurrected motioneye and feed all of the HLS streams there and then reverse proxy that single service instead. currently what im doing but with wyze hacks instead since the bridge isnt playing well with one of my Unifi AP's

**Comment by mitchross** [comment]
You didnt set a network in the service. 


wyze-bridge:
      network:
             homeinfra-net

**Comment by maxfield-allison** [comment]
can't believe I missed that. embarrassing lol

**Comment by alex-oswald** [comment]
The network is setup in my compose file.

```
networks:
  default:
    external: true
    name: homeinfra-net
```

**Comment by maxfield-allison** [comment]
but it is not in the service definition for wyzebridge. meaning it is not attached to the same network as traefik. 

```

services:
  wyze-bridge:
    image: 'mrlt8/wyze-bridge:latest'
    container_name: 'wyze-bridge'
    restart: 'unless-stopped'
    network:
      - homeinfra-net
```
