### ISSUE TITLE
How to use this with Frigate NVR

### ISSUE THREAD

**Issue by kelvincabaldo07** [mrlt8/docker-wyze-bridge#554]
Hi,

I am new to this and would like to use it to connect my 3 Wyze Cam V3 to Frigate but i noticed that the ports used by Frigate and this one are the same for the RTMP and Web UI. i tried changing the web UI ports on both systems but i cant seem to access both at the same time. I tried putting the Frigate to 5001 and kept the wyze bridge to 5000 and vice versa to no avail. any guidance will be greatly appreciated.
Thanks!

**Comment by mrlt8** [comment]
Does something like this in your bridge docker-compose.yml work?

```yaml
ports:
    - 1936:1935 # RTMP
    - 8554:8554 # RTSP
    - 8888:8888 # HLS
    - 5001:5000 # WEB-UI
environment:
    - WYZE_EMAIL=myemail@mailbox.com # Replace with wyze email 
    - WYZE_PASSWORD=password # Replace with wyze password
    - WB_RTMP_URL=rtmp://my.host.or.ip:1936/
```
