### ISSUE TITLE
HTTP Stream shows black banner on top and bottom of image

### ISSUE THREAD

**Issue by kevinleberge** [mrlt8/docker-wyze-bridge#63]
I'm using my streams in Magic Mirror using MMM-iFrame-ping module...  works great, except there's a black banner on top of the stream I can't get rid of. When I check the HTTP stream in my browser its the same thing, showing the top and bottom black bar.

How can I remove that?  Is it some code in the docker image files that's rendering the stream with the top/bottom banner?

Thanks!

![image](https://user-images.githubusercontent.com/12489509/128616951-65528cfc-f18a-49be-94d5-ce5b28dac8ac.png)
![image](https://user-images.githubusercontent.com/12489509/128616966-92c8a32d-722a-4870-bedb-a4c7ea1c6a92.png)

**Comment by mrlt8** [comment]
I believe the black bars are coming from here:
https://github.com/aler9/rtsp-simple-server/blob/1987572b67715315666338efdd5127f8e559a342/internal/core/hls_remuxer.go#L36-L40

could you use one of the other streams or link directly to the hls m3u8? 
`http://localhost:8888/camera-nickname/stream.m3u8`

**Comment by kevinleberge** [comment]
> I believe the black bars are coming from [here](https://github.com/aler9/rtsp-simple-server/blob/1987572b67715315666338efdd5127f8e559a342/internal/core/hls_remuxer.go#L36-L40)

That is exactly what it is!  I found it in the live code, but couldn't figure out where it is in my docker file. I have no idea how to edit the source files of my docker. You linked to the source here so maybe I'll be able to figure it out... unless you can offer any other insight I'd be happy to take any more help you can give.

I will try to use the direct stream. Thanks for all your help! This bridge rocks!

**Comment by mrlt8** [comment]
That's part of rtsp-simple-server, so you'd probably have to recompile that and then pull it into the container.
I think it would be easier to just set up a basic html page and embed your m3u8 in that.

and if you needed a server to serve the file, you could use something like this in your docker-compose:
```yaml
    web:
        container_name: nginx
        image: nginx:mainline-alpine
        restart: always
        ports:
            - 8080:80
        volumes:
            - /path/to/my/local/camera.html:/usr/share/nginx/camera.html
```
