### ISSUE TITLE
Home Assistant add-on / Hardware acceleration?

### ISSUE THREAD

**Issue by WarrenSchultz** [mrlt8/docker-wyze-bridge#769]
Is there a way to have the Home Assistant add-on use the configuration described here?
https://github.com/mrlt8/docker-wyze-bridge/wiki/Hardware-Acceleration

**Comment by mrlt8** [comment]
Not right now, but potentially. I believe we'd need to map the appropriate devices in the config.

Could you try the HW branch from the [edge repo](https://github.com/mrlt8/edge-repo) with the appropriate `H264_ENC` in the config?

**Comment by bobloadmire** [comment]
I can't get this addon to work smoothly on my rpi4, it would be cool to see if this would fix it.

**Comment by mrlt8** [comment]
Are you getting any error with the HW branch?

**Comment by bobloadmire** [comment]
Sorry, I meant I can't get standard production version to run well, webrtc is borked and HLS is super janky. So I was wondering if he acceleration would help

**Comment by mrlt8** [comment]
There's currently a bug all the way upstream in pion that is causing the webrtc issue in v2.1.

Can you try opening the rtsp stream in something like VLC and see if you still have the same issues?

**Comment by WarrenSchultz** [comment]
Sorry, I thought I'd responded to this previously.
So, I attempted to make this work in my Hyper-V environment with a partitioned GPU attached to the VM, but hardware encoding wasn't working. Figuring that I had a configuration/compat issue with my setup, I dropped back to deploying Wyze Bridge as a container using the latest-hw branch, but I had the same issue. I need to dig up logs for you. 
What is the most useful info for me to look for/which logs/etc?
Thanks!

**Comment by mrlt8** [comment]
Can you post your docker-compose.yml with your credentials removed?

Could also try to see if there are any ffmpeg related issues with the environment variable: `- DEBUG_FFMPEG=True`

**Comment by WarrenSchultz** [comment]
@mrlt8 Thanks for the debug tip, I didn't see that on the advanced options page until I searched for it just now.

So, good news, I got it working after seeing the logged error "Cannot load libcuda.so.1"

Did some digging around the net, and made some modifications, and it's working now. The main addition over what I had previously was the deploy section of the yaml hierarchy.
```
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest-hw
        devices:
            - /dev:/dev
        deploy:
            resources:
                reservations:
                    devices:
                    - driver: nvidia
                      count: 2
                      capabilities: [gpu]
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            - WYZE_EMAIL=REDACTED
            - WYZE_PASSWORD=REDACTED
            - MQTT_DTOPIC=homeassistant
            - H264_ENC=h264_nvenc
            - FORCE_ENCODE=True
            - DEBUG_FFMPEG=True
            - NET_MODE=LAN
            # - SNAPSHOT=HLS
            # - ROTATE_DOOR=True
            # - LLHLS=true
            - FILTER_NAMES=AstroCam
            - NVIDIA_DRIVER_CAPABILITIES=all
            - NVIDIA_VISIBLE_DEVICES=all            
#            - FRESH_DATA=true
```

A follow-up question though. Since enabling the hardware encoding, I see the option to go to WebRTC from the video option below, but not to access the stream directly from the in-window dialog:
![image](https://user-images.githubusercontent.com/8450968/232361465-98e520b5-af41-4bd0-8dec-5a63b0095444.png)

Additionally, I noticed that when (in theory?) I'm using the WebRTC stream in the gallery view, it has more latency with realtime than watching the stream on 8889. Although, if I'm reading the browser inspect view correctly, it may actually be playing HLS currently instead of the set WebRTC.

Let me know if you want me to do more testing on the container config.
