### ISSUE TITLE
un-reliable in my case, not sure why

### ISSUE THREAD

**Issue by balajeek** [mrlt8/docker-wyze-bridge#77]
I have setup this docker for 2 weeks + and really had hard time trying to make this work with v2,v2 pan,v3
initially v2 and v3 worked like magic and i setup frigate and all was well.  had problem with pan it kept coming as error, initially i thought i could be camera problem.  now that i am running wyze-bridge and frigate, i pretty much check frigate videos few times a day and suddenly few camera feeds are frozen, i check in wyze app and they seem work, then i restart wyze-bridge and all comes back again, lately i been restarting wyze 3-4 times a day to keep it alive.  

Is it just me, is it just my camera's going bad, or is it my config is not good yet ?

The developer seem very responsive and helpful and he tried to help me to solve, but i am still struggling.

here is my docker-compose, commented are all things i tried to make it work with no result:

```
wyze-bridge:
    image: mrlt8/wyze-bridge:latest
    container_name: wyze-bridge
    network_mode: host
    restart: always
    build: 
      context: ./app
      # dockerfile: Dockerfile.arm
    environment:
      - LAN_ONLY=True
      - WYZE_EMAIL=***
      - WYZE_PASSWORD=***
      #- RTSP_PROTOCOLS=tcp
      #- DEBUG_FFMPEG=True
      #- FILTER_NAMES=v3 outdoor, reef
      #- FILTER_MODEL=Pan
      #- FILTER_MODE=BLOCK
      #- QUALITY=HD
      #- RTSP_RTSPADDRESS=:8555
```

**Comment by balajeek** [comment]
I like to start over with just one v3 camera (which does not have rtsp native)

What config you suggest i put it?

**Comment by mrlt8** [comment]
First, I'd suggest checking your wifi. Official wyze [support documentation ](https://support.wyze.com/hc/en-us/sections/360006007472-Setup-Connectivity) has some suggestions. Also try googling your router brand + wyze to see if others have issues. 

There's a similar discussion over on #33  where this seemed to have helped:
- RTSP_PROTOCOLS=tcp
- RTSP_READTIMEOUT=30s
- RTSP_READBUFFERCOUNT=8192

Try something like this:

```yaml
version: '3.8'
services:
    wyze-bridge:
        image: mrlt8/wyze-bridge:latest
        container_name: wyze-bridge
        restart: always
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
        environment:
            - WYZE_EMAIL=
            - WYZE_PASSWORD=
            - LAN_ONLY=True
            - FILTER_MODEL=v3
            - RTSP_PROTOCOLS=tcp
            - RTSP_READTIMEOUT=30s
            - RTSP_READBUFFERCOUNT=8192
```
