### ISSUE TITLE
Camera Commands feedback

### ISSUE THREAD

**Issue by jhansche** [mrlt8/docker-wyze-bridge#799]
https://github.com/mrlt8/docker-wyze-bridge/wiki/Camera-Commands

> This is a work in progress and feedback would be appreciated

I wasn't sure how you wanted to receive this feedback, so I'm putting it here.

> Send basic command to the camera over the WebUI's API or MQTT:
>
> API: Make a GET request to /api/<camera-name>/<command>
> MQTT: Publish a command to the topic wyzebridge/<camera-name>/cmd
> Can be disabled with DISABLE_CONTROL=True.

There are a few issues here that kind of get in the way of being able to use them effectively (at least in HA). Depending on use case, pretty much everything is possible... The question is how much effort will it take, and how many helpers and automations need to be cobbled together for it to work.

Generally speaking, there are 2-3 options for adding these commands to HA:
1. As a script: simple MQTT publish or `resful.*` service call. This is the least useful option, but also the least problematic. We can create a service for every individual command we want to trigger.
2. As an mqtt.switch (or .select): The available configuration options _mostly_ work to allow exposing a switch here. But there are some downsides (see below)
3. As a restful.switch: Doesn't really work for setting the value, but could work as a restful.binary_sensor to show current state.

---

For mqtt.switch:

* There's no existing way to "ask" for the `get_night_vision` command in order to populate the initial state (or maybe I'm just not seeing it). So on HA startup, the state is "unknown" until you toggle it. The "state_topic" config will only listen to that topic, but doesn't have a way to ask for the initial value (i.e. by sending get_night_vision).
* The "command_topic" works fine for sending the payload_on/payload_off value for `set_night_vision_off` and `set_night_vision_auto` (or `_on`, if that's what you want).
* To make matters worse, since everything is all happening over one single topic (the commands we send, as well as the responses to those commands, for ALL possible commands), using state_topic to watch for the state_on or state_off values, is extremely fragile.
  For example, if you have one switch for `night_vision` and another switch for `status_light`, commands and responses for both of those will all be sent and received over a single topic, and that means the night vision mqtt.switch will also be monitoring the topic payloads (both outgoing and response) and receiving payloads for the status light switch. I don't see a way to do any topic payload filtering in the mqtt.switch integration, so all we can do is add conditions to the value_template, which **WILL** break whenever it sees a payload that belongs to a different command.

Here's an example of a _generally_ working night vision switch:
```
mqtt:
  switch:
    - name: wyze cam night vision
      command_topic: wyzebridge/camera-name/cmd
      payload_off: "set_night_vision_off"
      payload_on: "set_night_vision_auto"
      
      # FIXME: same topic for send and receive
      state_topic: wyzebridge/camera_name/cmd

      # response: {"cmd": "get_night_vision", "status": "success", "response": "3"}
      # response: {"cmd": "set_night_vision_auto", "status": "success", "response": "1"}
      # What about other payloads (like the set* commands, or other non-night-vision commands)? How do we filter these?
      value_template: "{{ value_json.cmd == 'set_night_vision_auto' or (value_json.cmd == 'get_night_vision' and value_json.response in ['1', '3']) }}"
      # 1=on, 2=off, 3=auto
      state_on: True
      # FIXME: any other topic messages will collide and cause it to become "off" incorrectly.
      state_off: False
      icon: mdi:lightbulb-night-outline
```
This works as long as we only ever send and receive the exact commands listed here. Any other commands will break the reported state.

To solve this issue, would involve one or more of these changes:

1. Different incoming (command) topic vs outgoing (response) topics.
3. Different topics for command groups; e.g. PUBLISH `topic=wyzebridge/<camera-name>/cmd/set_night_vision` `payload=auto`; and LISTEN `topic=wyzebridge/<camera-name>/cmd/get_night_vision` (such that this topic will be published any time the night vision value changes 🤔 

---

For a Restful entity, I didn't even get a chance to test it really, because the restful.switch integration doesn't seem to support a `GET` method for writing a state change - it only supports POST, PUT, and PATCH. It has options for body_on and body_off, but no option to change the resource (ie. URL) for the on or off states. So performing a `GET http://bridge:5000/api/camera-name/set_night_vision_off` vs `set_night_vision_auto` is not something that the restful component seems to be able to accomplish.

If we changed the API to allow POST/PUT/PATCH with a JSON command or value body, that would be way easier to support with the restful component. For example:
```
curl -X POST -v 'http://bridge:5000/api/camera-name/set_night_vision' -d '{"night_vision": "auto"}' # or '1|2|3'
curl -X PUT -v 'http://bridge:5000/api/camera-name/night_vision' -d 'off'  # or -d '1|2|3'
curl -X GET -v 'http://bridge:5000/api/camera-name/night_vision'  # response 1/2/3
```
This makes the endpoint more restful-friendly, and allows the restful.switch to work properly with it.

---

I know both of these significantly increase the complexity of both the REST API and the MQTT pub/sub architecture. But I just don't think that the current implementations work well with Home Assistant, or possibly other integrations for that matter.

To make this work properly, we would need to use something like an input boolean, paired with multiple automations (one to set the values over MQTT on manually changing, and one for triggering a state change from MQTT responses), since we are able to filter what MQTT payloads will allow an automation trigger to proceed, which we cannot do with mqtt.switch/etc.

We could probably do something similar as well with the REST API, using a combination of an input boolean, and multiple `rest_command` services for setting on/off/auto, and a restful.binary_sensor for obtaining the current state; plus automations to handle the input_boolean syncing.

So basically, it is possible to do ... it just takes _a lot_ of "doing", to get it right.

Another way to achieve this would be a custom component that can look up the available wyze bridge cameras, and expose switches or buttons (etc) for all the available commands, backed by the mqtt or rest api.

---

I also don't see commands for toggling these options on the Pan Cam v3:
* Privacy Mode (rotates the camera straight down and turns off the camera feed)
* Pan Scan (cycles through waypoint presets, 10 seconds at a time)
* Track Motion (pans the camera to automatically follow motion)
