### ISSUE TITLE
Using docker + home assistant

### ISSUE THREAD

**Issue by amcolash** [mrlt8/docker-wyze-bridge#853]
Hi! I love this project and have been using it a lot without the home assistant integration until trying recently. I have a server that has home assistant core running via docker. Since I do not want a dedicated home assistant device (server does a lot of other things), I tried added the integration with the various ENV vars mentioned in the wiki. Since I am using the docker version of HA, I cannot use any HA integrations directly 😢 

Here is my relevant config for `docker-compose.yml`. Note: I needed to use the `extra_hosts` setting to enable this container to talk with my other mqtt broker. It is definitely working though without any issue in the logs.

## docker-compose
```
wyze-bridge:
  container_name: wyze-bridge
  restart: unless-stopped
  image: mrlt8/wyze-bridge:latest
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - ./tokens/:/tokens/
  ports:
    - 1935:1935 # RTMP
    - 8554:8554 # RTSP
    - 8888:8888 # HLS
    - 8889:8889 #WebRTC
    - 8189:8189/udp # WebRTC/ICE
    - 5005:5000 # WEB-UI
  environment:
    - WYZE_EMAIL=************
    - WYZE_PASSWORD=************
    - MQTT_HOST=host.docker.internal:1883
    - MQTT_DTOPIC=homeassistant
```

## MQTT
Here is relevant info published to my mqtt broker - it seems like everything is there?

### HA Auto discovery

![Screen Shot 2023-06-13 at 4 44 15 PM](https://github.com/mrlt8/docker-wyze-bridge/assets/8282413/d5eef5c7-2148-4a8b-b7e3-0bcb654ad719)

Config Value:
```json
{
  "device": {
    "name": "Wyze Cam Garage",
    "connections": [
      [
        "mac",
        "D03F274B93CC"
      ]
    ],
    "identifiers": "D03F274B93CC",
    "manufacturer": "Wyze",
    "model": "WYZE_CAKP2JFUS",
    "sw_version": "4.36.10.4054",
    "via_device": "docker-wyze-bridge v2.3.0"
  },
  "topic": "wyzebridge/garage/image",
  "icon": "mdi:cctv",
  "name": "Wyze Cam Garage PREVIEW",
  "uniq_id": "WYZED03F274B93CCPREVIEW"
}
```

### Wyze bridge state

![Screen Shot 2023-06-13 at 4 43 52 PM](https://github.com/mrlt8/docker-wyze-bridge/assets/8282413/daa3e390-685b-4cc3-baea-505cfb072b88)

It looks like everything is showing up as expected, but HA isn't showing the devices. I have a handful of other MQTT devices and they work fine with a very similar config + state setup. Is there anything else needed here? I am happy to dig deeper and provide more info if needed.
