### ISSUE TITLE
2FA Daily

### ISSUE THREAD

**Issue by HOMESEERDUDE** [mrlt8/docker-wyze-bridge#865]
For the past few days, my bridge  stops, and required me to re authenticate through Wyze.   It then begins working again immediately. 
 Any idea why?

**Comment by mrlt8** [comment]
Hmm. That is strange as it should be able to use the refresh token instead of logging in again. 

Can you see if there are any errors in the logs?

You may also want to see if setting an API_KEY and API_ID helps:

https://github.com/mrlt8/docker-wyze-bridge/wiki/Two-Factor-Authentication#wyze-api-keyid

**Comment by mrlt8** [comment]
You'll need to set it as an environment variable for your container.

There have been a couple of updates. Do you have some kind of automation to update the container automatically? 

You could also volume map the `/tokens` directory locally to have your data persist.

**Comment by HOMESEERDUDE** [comment]
Yes, I use watchtower.  Thank you.  So, I should put /tokins         apikeyxxxxxx    at the bottom of the volume list?

**Comment by HOMESEERDUDE** [comment]
Do I just map the key id?  The api has xxxxxxx1234 by it

**Comment by mrlt8** [comment]
something like this in your docker-compose.yml

```yaml
    ...
    environment:
        - WYZE_EMAIL=
        - WYZE_PASSWORD= 
        - WB_IP=192.168.1.122
        - API_ID=My-Unique-App-ID-From-WYZE
        - API_KEY=MySecretKeyFromWyze
    volumes:
        - /path/to/local/tokens/:/tokens/
```
