### ISSUE TITLE
How would I feed a webrtc feed to frigate?

### ISSUE THREAD

**Issue by kevkid** [mrlt8/docker-wyze-bridge#968]
I am using this bridge to feed into a go2rtc stream input. I am a little unsure as to how we get the proper url? Seems like I have to echo a command into it?

Here is what my stream looks like:

```
go2rtc:
  streams:
    back_side: webrtc:http://<bridge-ip>:8889/front-porch-cam
     
    #I also tried This worked for a little while and doesnt work anymore
    #webrtc-wyze:    webrtc:http://<bridge-ip>:5000/signaling/front-porch-cam?kvs#format=wyze
```
When visiting: `http://<bridge-ip>:8889/front-porch-cam` I am greeted with the actual webrtc stream. But I have no idea how I would feed this into frigate?

**Comment by mrlt8** [comment]
WebRTC is still a work in progress. Can you try the rtsp stream instead?
```yaml
go2rtc:
  streams:
    back_side: 
      - rtsp://<bridge-ip>:8554/front-porch-cam
      - rtsp://<bridge-ip>:8554/front-porch-cam-sub # optional sub-stream
    # or use ffmpeg if the video is too glitchy:
    back_side_2: ffmpeg: rtsp://<bridge-ip>:8554/front-porch-cam
```
I'm currently working on integrating go2rtc directly into the bridge, but still need to work out some issues.
