### ISSUE TITLE
Unable to install on rPi 4 running Home Assistant

### ISSUE THREAD

**Issue by backslashV** [mrlt8/docker-wyze-bridge#98]
At the docker-compose up --build step, I get

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: error while creating mount source path '/config/www/repos/docker-wyze-bridge': mkdir /config: read-only file system.
```

My docker-compose.yml file:
```
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: always
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
        # Uncomment to use a pre-built image:
        # image: mrlt8/wyze-bridge:latest
        # or build from source:
        build: 
            context: ./app
            dockerfile: Dockerfile.arm 
        environment:
            - WYZE_EMAIL=mywyzeemail
            - WYZE_PASSWORD=mywyzepass
            - FILTER_NAMES=Cam
            #- LAN_ONLY=True
            - DEBUG_FFMPEG=true
            - FFMPEG_CMD=-i - -vcodec copy -f rtsp rtsp://0.0.0.0:8554/
        volumes: 
            - ./tokens:/tokens/
```

How can I fix this?
